### ISSUE TITLE
Update UX to render from GCS bucket folders

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#103]
```cucumber
GIVEN the updated backend
WHEN the frontend loads
THEN it has a similar feel to before
AND uses the GCS_BUCKET prefixes in the url
AND has a link back to the source test-grid, gcsweb, spyglass report
```

### Per Job Links

- Spyglass: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/35462
- GCSWeb: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/35462/
- Gubernator: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/35462

### Test Overview:
- https://prow.k8s.io/job-history/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce
- https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default
- https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default

**Comment by hh** [comment]
I think a link to spyglass is enough as it links to the other areas

**Comment by zachmandeville** [comment]
This is a part of commit e576e47e193dfe04974e890f711386e3c5061ac8.  When you click on a release, you'll see the sunburst load and details about its release, bucket, job, and a link to the spyglass page.

**Comment by hh** [comment]
Let's simplify the link to the prow/spyglass but just list the job_bucket/number:
[ci-kubernetes-e2e-gci-gce/34681](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/34681)

**Comment by hh** [comment]
We may at some point render directly from GCS buckets, but the documented flow to pull them into place is enough for now.
