### ISSUE TITLE
Reduce feature friction

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#105]
```cucumber
GIVEN changes in the data
WHEN we need to write a new feature
THEN minimal changes in the plumbing will be necessary
```

Let's spend a few days exploring some options to use static files or simplify our usage of feathers.

**Comment by hh** [comment]
@dankohn mentioned https://github.com/cncf/landscape loading JSON files directly

We also talked about possibly flattening into an  sqlite database.

Devstats has a multi-database merge and import process, but I believe this is only used to export json.

https://github.com/cncf/devstats/blob/master/ARCHITECTURE.md#architecture

I'd like us to think of ways we can process as much of the data as possible before hand and load static files if possible to remove the dependency on a backend. This way we can package the data with the netlify release.

**Comment by devaii** [comment]
Research being tracked in #115

**Comment by zachmandeville** [comment]
By revising our data definition for endpoint, and loading the json directly from a bucket, it simplified the logic needed in our front end considerably.  Within the scope of the ticket description, I would say this feature friction has been reduced.
