### ISSUE TITLE
Research Alternative Database & Backend Options

### ISSUE THREAD

**Issue by devaii** [cncf/apisnoop#115]
```feature
Given that we are unsatisfied with the current back-end/front-end architecture 
When we have found and agreed on a way to remedy this
Then we can move onto issue #105 
```

**Comment by zachmandeville** [comment]
We can run this without a backend, if we are not doing routing.  IF apisnoop always displays results for a single job result (and can then be deployed for all job results), then the architecture can just be json files loaded directly.
