### ISSUE TITLE
Website glitches when hovering over graph's ring

### ISSUE THREAD

**Issue by mgdevstack** [cncf/apisnoop#116]
While hovering over the graph, at certain categories like certificates, apiextensions etc webpage disappears.

![image](https://user-images.githubusercontent.com/8110509/54338096-f00c9900-4656-11e9-98e1-ba11bcb94e25.png)

**Comment by hh** [comment]
@mgdevstack can you take a look at dev.apisnoop.cncf.ci

**Comment by zachmandeville** [comment]
This has been fixed through some of the underlying changes in #201
