### ISSUE TITLE
Website UI Issues

### ISSUE THREAD

**Issue by mgdevstack** [cncf/apisnoop#117]
This is an umbrella issue to express multiple required fixes associated with landing/main page.
![image](https://user-images.githubusercontent.com/8110509/54338480-07985180-4658-11e9-97dd-967fdbbe9e2c.png)

- [ ] 1. By default show, coverage reports/graphs of master branch. (URI may have master) 
e.g. https://apisnoop.cncf.io/release/master
----
- [ ] 2. Good to have dropdown button for releases, master as topmost entry(default selected), Once clicked on release, show all data specific to that release, URI may have relase number.
e.g. https://apisnoop.cncf.io/release/v1.14.0-alpha.2.454
----
- [ ] 3. Show list of all e2e if we click on the graph and are in zoomed state.
Let's say in above pic it shows (5/15 total tested) meaning (5 are Conformance out of 15 e2e). So all e2e should be listed.

**Comment by mgdevstack** [comment]
I'm a bit confused with (5/15 total tested). What does it mean?
(Conformance e2e/all e2e) or (tested endpoints/ all available endpoints)?

**Comment by hh** [comment]
Why are we not listing tests for stable / batch / getBatchV1APIResources

**Comment by zachmandeville** [comment]
There was an overall change in format and styling as part of #201 , @hh and @mgdevstack , including language to make our testing coverage more clear.  I'd love to hear yr thoughts on some of these improvements!

**Comment by hh** [comment]
I think the work looks great! Thanks for integrating @mgdevstack's suggestions.
