### ISSUE TITLE
Figure out the mapping for API Endpoint to SIG/OWNERS

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#13]
This would allow us to narrow scope down a a SIG and give them a view into the specific data that interests them. We could possible extend that to specific github user/owners.

This will require understanding the structure of the api-machinery mappings, likely beyond what is available in [kubernetes/community/sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml)

**Comment by hh** [comment]
- [ ] We need to add sigs to kubernetes/pkg/apis/*/OWNERS

**Comment by Riaankl** [comment]
Issue Closed: Stale / Clean-up
