### ISSUE TITLE
Going to a valid URL returns the correct page, and not a 404

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#141]
```feature
Given the app's ability to adjust the url based on filters and queries
And the inherent idea to be able to share those urls
When you enter a url generated by apisnoop
Then it returns the corresponding page with correct sunburst, zoom levels, and other filters
```

**Comment by zachmandeville** [comment]
This is a breaking change based on the implemented ci pipeline, and changing which service handles the routing of our frontend.  We've moved from having netlify manage the routing to doing it ourselves on an [express](https://expressjs.com/) server that's implemented through [feathers](https://feathersjs.com/).  So we need to adjust our code accordingly.

**Comment by hh** [comment]
Thanks @zachmandeville !
