### ISSUE TITLE
Update import code to ignore discovery hits

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#145]
Discovery process at the beginning of each test hits the same endpoint every time.
We need to update import code to not mark as hit if it's at step X in the current test, where X matches the discovery process.

![image](https://user-images.githubusercontent.com/31331/55106232-4982c680-5133-11e9-97ac-a3a6f11af23b.png)

**Comment by hh** [comment]
Discovery process at the beginning of each test hits the same endpoint every time.
We need to update import code to not mark as hit if it's at step X in the current test, where X matches the discovery process.

![image](https://user-images.githubusercontent.com/31331/55106232-4982c680-5133-11e9-97ac-a3a6f11af23b.png)

**Comment by hh** [comment]
#178 should fix this @spiffxp do you have any feedback?

**Comment by hh** [comment]
The current filter is static, but it would be nice to revisit and create some dynamic logic on identifying the discovery process.

**Comment by zachmandeville** [comment]
Closing due to staleness, but can be reopened.  You can view current roadmap here: https://github.com/cncf/apisnoop/blob/master/org/roadmap.org
