### ISSUE TITLE
Add OWNERS file for Prow

### ISSUE THREAD

**Issue by devaips** [cncf/apisnoop#147]
# Request: Add OWNERS file to repo for Prow

## Short description:

- Current state:
  - There is no OWNERS file, so we cannot use Prow to approve PRs.
- Desired state:
  - OWNERS file in repo with authorized usernames

### Tasks:
- [x] Add OWNERS file to repo with current authorized users.

**Comment by hh** [comment]
Initally Added: https://github.com/cncf/apisnoop/commit/f2a4c9c722f632af1ecb5a7eb805f76893f732d6#diff-37ffc11190043a72e49391017a305d3a

Last few fixes:
https://github.com/cncf/apisnoop/commit/4abb1ac94d214e3d7849ed03b01cc999cafc9927#diff-37ffc11190043a72e49391017a305d3a

Checking with `/autocc`
/autocc

```
/auto-cc
Manually request reviews from reviewers for a PR. Useful if OWNERS file were updated since the PR was opened.
```

```
Description
The blunderbuss plugin automatically requests reviews from reviewers when a new PR is created. The reviewers are selected based on the reviewers specified in the OWNERS files that apply to the files modified by the PR.

Events handled
[GenericCommentEvent (any event for user text), pull_request]

Configuration(global)
Blunderbuss is currently configured to request reviews from 2 reviewers.```

**Comment by hh** [comment]
We can revisit this, with more strict permissions later, but we now have an OWNERS file.
