### ISSUE TITLE
Fix up apisnoop.cncf.ci

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#15]
- [x] feature the all-in chart
- [x] link to the repo
- [x] generally look nicer
- [x] https / let's encrypt

**Comment by rohfle** [comment]
https done

**Comment by dankohn** [comment]
Great!

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by rohfle** [comment]
Mockup of better looking UI
![export-v1](https://user-images.githubusercontent.com/21077341/40943703-3d2c6dee-68a6-11e8-9bf7-cddc494df052.png)

Now deployed to https://apisnoop.cncf.io/

Right now its just a static build.
[apisnoop-static.tar.gz](https://github.com/cncf/apisnoop/files/2070097/apisnoop-static.tar.gz)

**Comment by hh** [comment]
Let's create some feature tickets off this for the capture button, data, history, export etc.

- [ ] 1) Capture (and upload via kubectl apply)
- [ ] 2) mockup of the data tab.

**Comment by rohfle** [comment]
### Future ideas
- Data tab - deep dive into the requests that are sent to each endpoint
- Export tab - export the data to csv
- Group charts - see differences across charts
- Easy deployment - potentially similar to Sonobuoy

**Comment by hh** [comment]
Grey out future features, remove visual bug related to dual line chartpaths.
