### ISSUE TITLE
Document APISnoop Vocabulary

### ISSUE THREAD

**Issue by devaips** [cncf/apisnoop#153]
# Request: 
## Short description:
There are a number of terms which may or may not match the larger K8s community. Terms should be researched, documented, and possibly changed to match the common definition.

- Current state:
  - Terms are used but not defined.
- Desired state:
  - Terms are explicitly defined and documented

### Tasks:
- [ ] Research usage of terms in greater k8s community
- [ ] Document definitions
- [ ] Make adjustments to usage as seen necessary

**Comment by devaii** [comment]
**Some terms which we should look into how we are currently using:**

Groups vs Category

Verbs vs Methods

Endpoints vs Kind

**Comment by zachmandeville** [comment]
also: level versus version?

**Comment by hh** [comment]
We don't need to change the names used within APISnoop, but we might be able to document where they come from better.

**Comment by hh** [comment]
This was a useful team exercise, we know have internalized the shared vocabulary of the k8s community.
