### ISSUE TITLE
Decide Whether We Seperate Verb from Endpoint Name

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#157]
# Request: Come to decision on formatting of our endpoint names and whether the verb should prepend the name

## Short description:

- Current state:
  - If there's an endpoint called "FooBarAuthorization" and it includes the verbs "List" and "Watch", then we will have two endpoitns in our sunburst: listFooBaurAuthorization and watchFooBarAuthorization"
- Desired state:
  - We either have them be a single endpoint with just its name, and the endpoint object ontains a list of its verbs.  Or we keep our current formatting with good documentation for why.

**Comment by devaii** [comment]
> a single endpoint with just its name, and the endpoint object contains a list of its verbs

This more closely matches OpenAPI spec, and implementation will be a part of https://github.com/cncf/apisnoop/issues/152
