### ISSUE TITLE
Make @cncf-ci bot comment with link to PR preview upon successful build.

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#159]

**Comment by hh** [comment]
/assign @devaii

I'd also like to ensure that:
- [ ] https://apisnoop.cncf.io is the primary url (currently that url redirects to https://apisnoop.cncf.ci)
- [ ] If possible use the *.apisnoop.io as the suburls for previews, though a quick looks makes me feel this will only work for branches... ie BRANCHNAME.apisnoop.io

While this is somewhat working, we'll need a loop in the ./hack/ci/netlify-pr.sh to wait for the latest-build.txt to appear. It might also be useful to ensure that the job output we are pulling in is actually from the commit that generated this PR preview.

You may need to look at some of the ENV vars related to the commit sha hash or similar to wait for the correct job output to be available.

**Comment by hh** [comment]
ENV work now merged.
