### ISSUE TITLE
Identify kapics+methods to drive POD api usage

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#16]
The CNCF is contracting help to write missing e2e tests for stable apis, specifically ones that make sense to promote to conformance tests.

POD API endpoints are extremely feature rich, have multiple implementations, and are used by everybody. This combination makes them of particular interest as we collect user journey data to prioritize which tests to write next. [SIG-Architecture May 10th discussion](https://www.youtube.com/watch?v=gCTLdzsqzaY&feature=youtu.be&list=PL69nYSiGNLP2m6198LaLN6YahX7EEac5g&t=3398)

The APISnoop team would like provide a list of popular POD K8s API endpoints and additionally the parameters/responses used by real world API consumers at the next sig-node meeting on June 13th.

To do so, we need to collect audit-logs while driving applications that use the POD API to it's fullest.

We are asking for help in identifying which applications we should focus on, in addition to help driving those applications to give us meaningful POD endpoint/verb parameters/responses.

Projects with existing e2e tests would be best, but we are willing to manually drive them if doing so can produce actionable data (based on real user journeys) to drive our conformance efforts.

/cc @cncf/kubernetes-conformance-team @kubernetes/sig-node-proposals

- [x] request feedback on how to drive kapics to use the pod api, and suggested kapics to choose first
  https://groups.google.com/d/topic/kubernetes-sig-node/6ZfFECC1sjc/discussion
- [ ] identify kapics that drive pods
- [ ] identify methods to drive pod api using kapics
- [ ] Present initial results to sig-node on June 13th meeting

**Comment by hh** [comment]
Attended the May 30th meeting, ran out of time, but was asked to present next time.

**Comment by hh** [comment]
The CNCF is contracting help to write missing e2e tests for stable apis, specifically ones that make sense to promote to conformance tests.

POD API endpoints are extremely feature rich, have multiple implementations, and are used by everybody. This combination makes them of particular interest as we collect user journey data to prioritize which tests to write next. [SIG-Architecture May 10th discussion](https://www.youtube.com/watch?v=gCTLdzsqzaY&feature=youtu.be&list=PL69nYSiGNLP2m6198LaLN6YahX7EEac5g&t=3398)

The APISnoop team would like provide a list of popular POD K8s API endpoints and additionally the parameters/responses used by real world API consumers at the next sig-node meeting on June 13th.

To do so, we need to collect audit-logs while driving applications that use the POD API to it's fullest.

I'm asking for help in identifying which applications we should focus on, in addition to help driving those applications to give us meaningful POD endpoint/verb parameters/responses.

Projects with existing e2e tests would be best, but we are willing to manually drive them if doing so can produce actionable data (based on real user journeys) to drive our conformance efforts.

/cc https://groups.google.com/d/topic/kubernetes-sig-node/6ZfFECC1sjc/discussion

/cc @cncf/kubernetes-conformance-team @kubernetes/sig-node-proposals

**Comment by hh** [comment]
We have been unable to identify kapics that 'fully' utilize the POD api on our own.
It seems the current drivers are the e2e tests themselves.
Should we focus on #17 or should this ticket also have some priority?

/cc @wangzhen127 @AishSundar @cncf/kubernetes-conformance-team

**Comment by AishSundar** [comment]
@hh my 2c is definitely to focus on [#17](https://github.com/cncf/apisnoop/issues/17) as priority since it will help us, as first step, identify the existing e2e tests (which hit APIs uncovered by current conformance tests) to promote to conformance. 

But I feel this issue should also be kept open (and given some priority) to help us with the next step in the process i.e., defining useful test scenarios for APIs uncovered by existing e2e tests.

**Comment by hh** [comment]
Spoke with @prydonius regarding helm chart usage and testing. We opened https://github.com/kubernetes/charts/issues/5899 to find which KAPICS w/ charts are heavily used.

**Comment by hh** [comment]
I see there is an open issue to [add support for Node audit logging](https://github.com/kubernetes/kubernetes/issues/39441) that I think is particularly relevant, but not useful yet.

**Comment by wangzhen127** [comment]
That one is for system journald logs, mostly for security purpose. It is not for API audit logging.

**Comment by hh** [comment]
This is now a discussion point vs an action. Will close, and leave as part of our history.
