### ISSUE TITLE
Make @cncf-ci bot comment when a build fails to provide info and links.

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#160]

**Comment by hh** [comment]
/assign @devaii 
Can you verify that this is working?

**Comment by devaii** [comment]
I created  PR https://github.com/cncf/apisnoop/pull/232 to test this.

It does not appear to be working.

**Comment by devaii** [comment]
Blocked by https://github.com/cncf/apisnoop/issues/234

**Comment by hh** [comment]
Done!
