### ISSUE TITLE
Add package.json into app.org

### ISSUE THREAD

**Issue by devaii** [cncf/apisnoop#162]
# Request: app.org can be run separately from rest of site/repo.

## Short description:

- Current state:
  - the repo can run local versions of our frontend or backend, but nothing else.
- Desired state:
  - the `app/` folder is a self contained app that runs separate from rest of apisnoop.

**Comment by zachmandeville** [comment]
Done as part of 9cefa511f8f35addea5d1c26c5cf1598b453ebef
