### ISSUE TITLE
Load data directly from JSON files

### ISSUE THREAD

**Issue by devaii** [cncf/apisnoop#163]
# Request: Make APISnoop frontend load from JSON files instead, of relying on Feathers to format and serve data.

## Short description:

interim: going thru our current pipeline. a deployment for each set of job results.

- Current state:
  - When you load APISnoop it shows multiple releases to choose from, and these route to their respective job results.
- Desired state:
  -  In new version you load APISnoop and it shows a single job result

### Tasks:
- [ ] (Add tasks to achieve desired state)

**Comment by zachmandeville** [comment]
This is the behavior in `app`, with the sunburst as an example of how this works.  See: 92933922fd5681798e5a8306b6b646e7dff8515b
