### ISSUE TITLE
Format data to better suit frontend needs

### ISSUE THREAD

**Issue by devaii** [cncf/apisnoop#164]
# Request: Our JSON is structured so endpoint info can be checked and cross-referenced easily, and there's no unnecessary complexity.

## Short description:

- Current state:
  - our endpoints.json is organized around operationId and method, but this may not be the smartest way.
- Desired state:
  -  We have a simple and clean structure that the site consumes easily.

**Comment by hh** [comment]
- endpoints.json:

```json
{
  "operationId": '',
  "path": '',
  "level": '',
  "category": '',
  "group": '',
  "version": '',
  "kind": '',
  "methods": [
    "get": {
      isTested: boolean,
      isConformance: boolean,
    },
    "watch": {
      isTested: boolean,
      isConformance: boolean,
    }
  ]
}
```

- user-agents.json

```json
[
"readFoo": [ "get"],
"readBar": ["get", "watch"]
]
```

**Comment by zachmandeville** [comment]
The json's output by snoopAuditLog.py follow this new structure.
