### ISSUE TITLE
Retrieve JSON objects from GCS Bucket instead of local file

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#166]
# Request: objects via GCS

## Short description:

- Current state:
  - Objects are loaded via local file paths
- Desired state:
  - Loading objects remotely via GCS (for Spyglass)

### Tasks:
- [x] Unblock CORS issue + GCS

**Comment by hh** [comment]
From https://medium.com/@kevinsimper/google-cloud-storage-cors-not-working-after-enabling-14693412e404

> If you experience that the Google Cloud Cors is not working even after you did “gsutil cors set cors.json gs://your-bucket/”, it may be because you are using the wrong root domain, only one of the domains will have the headers enabled on the request, so

> storage.googleapis.com/your-bucket ⬅ will not have headers

> your-bucket.storage.googleapis.com ⬅ will have cors headers

> Something very easy to overlook and Google by default links to the storage.googleapis.com/your-bucket from the interface, so if you copied that and thought it work.

**Comment by zachmandeville** [comment]
we needed to be explicit in our bucket for not only the domains we allow access, but also the domain ports.  Adding the correct port fixed the issue.

All resources are added to the app's state as of b03d3373e7293ff9f952bd2689d3043e3e4189b2
