### ISSUE TITLE
Map existing e2e tests to APIs they cover

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#17]
In analyzing some of the existing e2e tests, specifically POD related APIs, it's become evident that the e2e tests are not one to one with the APIs, as most of the well written tests (emulating user stories) hit more than one API.

To assist with [Identifying e2e tests to upgrade to Conformance tests](#14), we need find a way to correlate our raw audit log entries to the tests that created them.

Some options to explore:
- [ ] Inject a parameter into the http requests identifying the e2e test that ends up in the audit-log entry
- [x] Dual time-series data syncing (record timestamps for start/finish for each test -- less exciting, but this got us across the line for our first dataset)

Open to other options, some type of injection is the cleanest.
I'll start by exploring what injection options are available.

/cc @fedebongio @AishSundar @wangzhen127

**Comment by hh** [comment]
Message sent to relevant groups for feedback:
https://groups.google.com/forum/#!topic/kubernetes-sig-testing/m57_-AB0muM

**Comment by rohfle** [comment]
>  Inject a parameter into the http requests identifying the e2e test that ends up in the audit-log entry

Another alternative to this could be requesting a specific endpoint when the e2e test begins and ends

ie `/apis/?mark=test-start&file=test/e2e/apimachinery/garbage_collector.go&message="`should delete pods created by rc when not orphaning"`

**Comment by hh** [comment]
Maybe we set the UserAgent for each api to include the current line-number / e2e test.
https://github.com/kubernetes/client-go/blob/d9cf97751096b28cbb73b091f61226e8ddd4ab42/rest/config.go#L86-L87
[thanks Morgan Harold Bauer](https://github.com/kubernetes/client-go/blob/d9cf97751096b28cbb73b091f61226e8ddd4ab42/rest/config.go#L86-L87)

**Comment by rohfle** [comment]
Maybe we could just wrap the e2e test script and parse the `.It()` stdouts and timestamp them then compare to the audit log entry timestamps

**Comment by hh** [comment]
Another option might when we detect a new test starting in the stdout, we curl out to an endpoint that will generate an audit-log entry.

With both stdout monitoring approaches we need to be aware of timing / interpolating the e2e test boundaries.

**Comment by rohfle** [comment]
@AishSundar Preliminary results using timestamps obtained from wrapping the e2e test script.

See https://github.com/cncf/apisnoop/tree/master/dev/e2e-audit-correlate to see how these were obtained.

The only step not in the scripts is running the following on the master of the test cluster before the e2e tests are started:

`nohup tail -f -n0 /var/log/kube-apiserver-audit.log 2>/dev/null &`

Results (14MB text file)
[20180605_e2e-test-endpoint-hits.txt.gz](https://github.com/cncf/apisnoop/files/2074062/20180605_e2e-test-endpoint-hits.txt.gz)

**Comment by hh** [comment]
Looks like there is [interest](https://groups.google.com/forum/#!msg/kubernetes-sig-api-machinery/R-z_NjiLzmg/h3ZbywwAAgAJ) in logging user-agent with audit-logging and setting user agent per-e2e-test. I'm going to create tickets for those.

**Comment by hh** [comment]
- [ ] [Set user-agent per test in e2e framework](https://github.com/kubernetes/kubernetes/issues/64790)
- [ ] [Add user-agent to audit-logging](https://github.com/kubernetes/kubernetes/issues/64791)

**Comment by AishSundar** [comment]
@rohfle this is awesome progress ! Thanks for such a quick turnaround ! A couple of ques aorund the results
* Was the outputfile (20180605_e2e-test-endpoint-hits.txt.gz) obtained by running all e2e tests our just the conformance suite?
* https://github.com/cncf/apisnoop/tree/master/dev/e2e-audit-correlate does not have much info on how to trigger the script post a test run. Would it be possible to qucikly out a README together?
* when you say "preliminary" results, are you working on making more improvements to this approach and/or focusing on another approach to corroborate results?

**Comment by rohfle** [comment]
- I ran all (or nearly all?) the e2e tests, not just conformance (it took many many hours and the audit log was around 1GB)
- I can put a readme together to explains things
- There are a couple of assumptions that I made to reduce complexity. I am using the console output from kubetest to determine when tests are run. I can detail these in the readme also. 

The assumptions are mainly:
1. The latency between kubetest writing to stdout and my program reading and detecting a new test is negligible. I measured 300us using the simulate-e2e.py script.
2. The time between the GCE master and the staging server I was running of were synchronised.
3. The mark `--------------` denotes a new test being run and this mark is found nowhere else in the e2e logs.

**Comment by AishSundar** [comment]
@rohfle thanks for the explanation and listing the assumptions. For now this is more than what we have and we can definitely use this data to narrow down our search to answer "which test case exercised the API". Looking forward to the README

Coming back to my one other previous ques, @hh are you actively working on "logging user-agent with audit-logging and setting user agent per-e2e-test"? Until we get data out of that we will use Rohan's report to guide test case promotion to conformance

**Comment by rohfle** [comment]
@AishSundar The README is live - https://github.com/cncf/apisnoop/tree/master/dev/e2e-audit-correlate. I've also included everything except the audit log (due to its size and potentially secret contents)
