### ISSUE TITLE
Ensure our data-gen script catpures all possible user-agents

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#173]
# Request: (Put request here. One liner.)
From 1.12 onward there should be multiple user-agents in our audit logs.  Historically, we've only captured the e2e useragent, but should make sure we've expanded to all.
## Short description:

- Current state:
  - useragents.json has a single entry: e2e
- Desired state:
  - all useragents in the audit log are  added to useragents.json

**Comment by hh** [comment]
Our logs now include and the UI has a filter for all user-agents.
