### ISSUE TITLE
Update from Static Discovery filtering to Dynamic

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#180]
In #145 @hh created a static list for filtering out discovery.
It's a temporary approach / stake in the ground.
@zz you had some thoughts, let's follow up here.

**Comment by hh** [comment]
This will be a requirement, as the static list had a wider impact than expected.

**Comment by zachmandeville** [comment]
Closing due to staleness, but can be reopened.  You can view current roadmap here: https://github.com/cncf/apisnoop/blob/master/org/roadmap.org
