### ISSUE TITLE
Check Podspec data of requests against OpenAPI spec

### ISSUE THREAD

**Issue by rohfle** [cncf/apisnoop#19]
At the moment we are just looking at methods and requestURIs of communications with kube-apiserver. We could expand this by looking at the request Podspec data submitted. Doing this we could:

- Obtain stats on individual field coverage in the Podspec
- Validate individual requests to the endpoint against the OpenAPI spec

There has been interest in using this feature to help efforts surrounding increasing conformance test coverage for POD APIs.

People interested: aish, zhenw

**Comment by zachmandeville** [comment]
closing due to staleness.  You can view an updated roadmap here: https://github.com/cncf/apisnoop/blob/master/org/roadmap.org
