### ISSUE TITLE
Continuous update of graph on README.md and apisnoop.cncf.ci from K8s master

### ISSUE THREAD

**Issue by rohfle** [cncf/apisnoop#20]
At the moment to update the graph we have to manually update both the image on the repo and the data on the web. This involves building from source, spinning up a K8s test cluster, running tests etc.

On a regular basis, we could automatically run the e2e conformance suite and collect logs on K8s master.
We could also automatically create an image for README.md so its picture is always up to date.

Prerequisites: Sessions, easy deploy and log collection.

Interested people: oomichi

**Comment by hh** [comment]
Going forward we will be pulling / generating visualizations directly from test-grid.
If we want, it might make sense to just pull this image directly from apisnoop.cncf.io for master, and possibly the graph of coverage rather than updating the image in the repo.

**Comment by hh** [comment]
We've updated from master (and the recent released), however we don't update the Readme.
I'm pulling this into current release for prioritization.

**Comment by devaii** [comment]
Continuous updates of APIsnoop data has been handled in issue #69.

We will update the image in the README upon every new release.
