### ISSUE TITLE
PR for kind merged to create auditlog in CGS

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#202]
# Request: PR for kind merged to create auditlog in CGS

## Short description:

- Current state:
  - The pr, https://github.com/kubernetes-sigs/kind/pull/457, is created but not yet merged.
- Desired state:
  - the pr is merged and audit loggins is a part of kind/hack/ci/e2e.sh

The progress for this is being tracked on the pr: https://github.com/kubernetes-sigs/kind/pull/457

**Comment by zachmandeville** [comment]
@hh , can you clarify the state and desired state of this request?

**Comment by hh** [comment]
This is a todo: https://github.com/kubernetes-sigs/kind/pull/457

**Comment by Riaankl** [comment]
Issue Closed: Stale / Clean-up
