### ISSUE TITLE
Export conformance stats into velodrome.k8s.io

### ISSUE THREAD

**Issue by rohfle** [cncf/apisnoop#21]
http://velodrome.k8s.io/dashboard
https://github.com/kubernetes/test-infra/tree/master/velodrome
> Velodrome is the dashboard, monitoring and metrics for Kubernetes Developer Productivity

Could be nice to export conformance stats to velodrome

**Comment by zachmandeville** [comment]
This is an interesting idea, but would do well with more discussion.  Could we submit the stats directly to velodrome everytime we generate new data?  Or is this suggesting there is an export button on apisnoop's web app that allows you to export results to velodrome?  The former option seems more practical, but this ticket is a part of the UX directory, which makes it seem like the latter.

**Comment by dankohn** [comment]
Note that Velodrome has largely been supplanted with k8s.devstats.cncf.io.
