### ISSUE TITLE
Make Filter Options Less Opaque

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#212]
# Request: the purpose and usage of our filters should be clear to any site visitor

## Short description:

- Current state:
  - We display a filter, but without explaining its use or what its filtering
- Desired state:
  - a less opaque section, whether that's a short explanatory text beneath the filter section, or a design that highlights their use more cleanly.

### Tasks:
- [ ] Decide upon design and method to increase clarity
- [ ] implement it in frontend.

**Comment by hh** [comment]
#263 seems to address this enough for my concerns.
