### ISSUE TITLE
our cncf-ci bot should not require sig-group every time

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#221]
# Request: when you open a ticket, you aren't prompted to add a sig group

## Short description:

- Current state:
  - every ticket gets a ping to add a group, but it's unclear what group we would add for an apisnoop specific ticket.
- Desired state:
  - it stops prompting, or we have an agreed group we add these tickets to.

**Comment by hh** [comment]
Fixed in https://github.com/ii/org/commit/bdf2aacca49c5f2c87831fa90dc93591c771a63d
