### ISSUE TITLE
Five or Six examples insights

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#229]
## Short description:

- Current state:
  - Difficult to comprehend featureset
- Desired state:
  - Links to several useful / actionable insights that might encourage others to explore further

### Tasks:
- [ ] Research some insights (5 to 6)
- [ ] Add those stateful urls as links to the left hand side

**Comment by devaips** [comment]
Issue https://github.com/cncf/apisnoop/issues/256 is for adding the examples to the side-bar.

**Comment by devaips** [comment]
## Potential Examples

**Show All Conformant APIs**

https://apisnoop.cncf.io/?zoomed=level-stable&showUntested=false&showTested=false&showConformanceTested=true

**Stable-Core Tested but Not Conformant Filter**

https://apisnoop.cncf.io/?zoomed=category-stable-core&showUntested=false&showConformanceTested=false

**Stable-Core Conformance Tests**

https://apisnoop.cncf.io/?zoomed=category-stable-core&showUntested=false&showConformanceTested=true&showTested=false)

**Stable Endpoints _Hit but Not Conformant_**

https://apisnoop.cncf.io/?useragents=%5B%5Ee2e.test%5D&showUntested=true&showTested=false&showConformanceTested=false&zoomed=level-stable

**Comment by dankohn** [comment]
The fourth URL above works for me but the first 3 give image errors. I suspect you're having URL escaping errors.

**Comment by devaips** [comment]
That's odd. They are all working for me. Though it did feel like they took a bit longer to load than usual; Approximately 3~ seconds after opening each link.

**Comment by dankohn** [comment]
Now working for me.

**Comment by devaips** [comment]
Good. What were the "image errors" you saw? Was the sunburst not loading, or something else?

**Comment by dankohn** [comment]
None of the images loaded, including even the favicon. I suspect it was a temporary Netlify issue.

**Comment by hh** [comment]
Thanks @zachmandeville and @devaips.
Thanks for the feedback @dankohn
