### ISSUE TITLE
Log all k8s client-go usage src+line using runtime.Caller 

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#23]
As we [add user-agent to audit-logging](https://github.com/kubernetes/kubernetes/issues/64791) and look into [setting user-agent per test in e2e framework](https://github.com/kubernetes/kubernetes/issues/64790) it got me thinking about wider reaching approaches.

If we add support in [kubernetes/client-go](https://github.com/kubernetes/client-go) to set the user-agent to the calling src code file and line number via [runtime.Caller](https://golang.org/pkg/runtime/#Caller), the resulting data would allow a community wide index of not only all API usage parameters and responses, but the links to the precise source code lines that were involved.

**Comment by hh** [comment]
Some primative examples:
https://play.golang.org/p/DOUnolRdz23

```
output:
called from main.testA:/tmp/sandbox563224353/main.go:11
called from main.testB:/tmp/sandbox563224353/main.go:14
called from main.testB:/tmp/sandbox563224353/main.go:15
```


```go
package main

import (
	"fmt"
	"runtime"
)

func apicall() {
	pc, file, line, ok := runtime.Caller(1)
	function := runtime.FuncForPC(pc)
	if ok && function != nil {
		fmt.Printf("called from %s:%s:%x\n", function.Name(), file, line)
	}
}

func testA() {
	apicall()
}
func testB() {
	apicall()
	apicall()
}

func main() {
	testA()
	testB()
}
```

**Comment by rohfle** [comment]
call to get the backtrace as a string:
https://golang.org/pkg/runtime/debug/#Stack

**Comment by rohfle** [comment]
Places which may be called by everything
https://github.com/kubernetes/client-go/blob/master/rest/request.go#L755
```golang
func (r *Request) Do() Result
```

https://github.com/kubernetes/client-go/blob/33bd23f75b6de861994706a322b0afab824b2171/rest/client.go#L94
```golang
func NewRESTClient(baseURL *url.URL, versionedAPIPath string, config ContentConfig, maxQPS float32, maxBurst int, rateLimiter flowcontrol.RateLimiter, client *http.Client) (*RESTClient, error) {
```

**Comment by rohfle** [comment]
Example call to client from Kubernetes API
```
// DeleteCollection deletes a collection of objects.                                                                                            
func (c *deployments) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {                                           
        return c.client.Delete().                                                                                                               
                Namespace(c.ns).                                                                                                                
                Resource("deployments").                                                                                                        
                VersionedParams(&listOptions, scheme.ParameterCodec).                                                                           
                Body(options).                                                                                                                  
                Do().                                                                                                                           
                Error()                                                                                                                         
}          
```

Call stack if we used ```Verb()``` (see above) would look like:
```
Verb()
Delete()
DeleteCollection()
....
TestFunction()
```

**Comment by rohfle** [comment]
Adding headers to the request
```golang
req, err := http.NewRequest("GET", "http://example.com", nil)
// ...
req.Header.Add("If-None-Match", `W/"wyzzy"`)
resp, err := client.Do(req)
// ...
```

**Comment by hh** [comment]
What if we add _content.UserAgent_ somewhere upstream, at a point where we can reliable find the caller?

https://github.com/kubernetes/client-go/blob/master/rest/request.go#L137
```golang
// NewRequest creates a new request helper object for accessing runtime.Objects on a server.
func NewRequest(client HTTPClient, verb string, baseURL *url.URL, versionedAPIPath string, content ContentConfig, serializers Serializers, backoff BackoffManager, throttle flowcontrol.RateLimiter, timeout time.Duration) *Request {
//...snip...
	switch {
	case len(content.AcceptContentTypes) > 0:
		r.SetHeader("Accept", content.AcceptContentTypes)
	case len(content.ContentType) > 0:
		r.SetHeader("Accept", content.ContentType+", */*")
	}
```

**Comment by rohfle** [comment]
It seems nicer to configure everything at that one point.

I guess the question is - is it more valuable to record the information about where the request is created, or where it is executed?

**Comment by rohfle** [comment]
Client interface
https://github.com/kubernetes/client-go/blob/master/rest/client.go#L43
```
type Interface interface {
	GetRateLimiter() flowcontrol.RateLimiter
	Verb(verb string) *Request
	Post() *Request
	Put() *Request
	Patch(pt types.PatchType) *Request
	Get() *Request
	Delete() *Request
	APIVersion() schema.GroupVersion
}
```

**Comment by rohfle** [comment]
`TestContext.*` and friends are generally set by `KubectlCmd`
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L2127

```golang
func KubectlCmd(args ...string) *exec.Cmd {
	defaultArgs := []string{}

	// Reference a --server option so tests can run anywhere.
	if TestContext.Host != "" {
		defaultArgs = append(defaultArgs, "--"+clientcmd.FlagAPIServer+"="+TestContext.Host)
	}
        [...]
```

**Comment by rohfle** [comment]
Where the flags are defined for the command line
```golang
func RegisterCommonFlags() {
	// Turn on verbose by default to get spec names
	config.DefaultReporterConfig.Verbose = true

	// Turn on EmitSpecProgress to get spec progress (especially on interrupt)
	config.GinkgoConfig.EmitSpecProgress = true

	// Randomize specs as well as suites
	config.GinkgoConfig.RandomizeAllSpecs = true

	flag.StringVar(&TestContext.GatherKubeSystemResourceUsageData, "gather-resource-usage", "false", "If set to 'true' or 'all' framework will be monitoring resource usage of system all add-ons in (some) e2e tests, if set to 'master' framework will be monitoring master node only, if set to 'none' of 'false' monitoring will be turned off.")
	flag.BoolVar(&TestContext.GatherLogsSizes, "gather-logs-sizes", false, "If set to true framework will be monitoring logs sizes on all machines running e2e tests.")

```

**Comment by rohfle** [comment]
### Strategy

1. Create a flag that turns on `User-Agent` logging in `TestContext`
2. Register the flag in `RegisterCommonFlags()`
3. ???
4. If the flag has not been set, then ???
5. Else, get a copy of the line number, function and backtrace using
```golang
	pc, file, line, ok := runtime.Caller(1)
	function := runtime.FuncForPC(pc)
	backtrace := string(debug.Stack())
	lines := strings.Split(backtrace, "\n")
```
6. Set in header in `Do()` and `DoRaw()` using
```golang
if (TestContext.AddDebugInfoToUserAgent) {
    r.Header.Add("User-Agent", `W/"kubetest [function_call(), parent_call(), root_call()]"`
}
[...] // make the request
```

**Comment by rohfle** [comment]
Committed to branch - https://github.com/ii/kubernetes/commits/feature_debug_user_agent

**Comment by rohfle** [comment]
Tools for parsing the stacktrace info out of the audit logs can be found here:
https://github.com/cncf/apisnoop/tree/master/dev/user-agent-stacktrace

**Comment by tallclair** [comment]
This level of client debugging doesn't feel like it belongs in the server-side logs. An alternative approach is to log sufficient information in the client-side logs to correlate the request with the audit logs. The two sets of logs could then be combined programmatically as needed.

The best way to do this would be to log the `audit-id` header that is returned on the api response, and can be used to uniquely identify the corresponding audit logs.

**Comment by hh** [comment]
My intention is for APISnoop to be able to infer critical user journeys for all _KAPICs*_ using a data driven approach.

My hope was to _easily allow anyone using kubernetes_ to contribute data by:

1. running a simple 'kubectl apply -f httpx://apisnoop.cncf.io/dynamic-audit-endpoint-guid/enable-callstack-clusterwide.yaml' similar to https://scanner.heptio.com
2. using their cluster as normal

Logging the call-stack via client-go would allow us to correlate user journeys for any _KAPIC_ without modifying client side logic or uploading call-stacks.

While the user-agent may be quite verbose, this is just a extremely specific user-agent.
SPNEGO authentication headers alone can be up to 12392 bytes. :)
Looking at the initial sets of data, I suspect 2048 would be sufficient for the max user-agent size limit.

With the above in mind, is there a suggested path that wouldn't take us to far into the woods?
OR would a 2k user-agent be a reasonable compromise?

_* Kubernetes API Consumer_

**Comment by hh** [comment]
@tallclair I'm pursuing the audit-id header and thinking about this approach.

I am trying to identify when an api call is being made from the same line of code / callstack without client side logging or logic _(so it can be enabled for any application using client-go)_. 

To limit exposing local path names and source, client-go could instead generate a hash of the data (generalized, so it's just the paths+linums under $GOPATH)?

This hash could be included in User-Agent, Audit-Id, or possibly a new Callstack-Hash, but only when configured to do so via a KUBE_CALLSTACK_HASH style env var. For now I'll use Audit-Id, but suggest it go elsewhere later.

Identifying usage patterns would not require a hash to callstack lookup, but it may be useful to generate it anyway, save it for possible upload.

**Comment by Riaankl** [comment]
Issue Closed: Stale / Clean-up
