### ISSUE TITLE
Summary Data Across all data sets within a single audit-sources.yaml

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#230]
This should give us prioritised summary list including endpoints / kinds to prioritize by noting who is using (and what data sets comprise the prioritization).

**Comment by zachmandeville** [comment]
closing due to staleness and that our methods for getting and exploring data has changed significantly from when this issue was opened.  You can view an updated roadmap here: https://github.com/cncf/apisnoop/blob/master/org/roadmap.org
