### ISSUE TITLE
Ensure https://apisnoop.cncf.io is the netlify production/master URL. Currently it redirects to https://apisnoop.cncf.ci

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#231]

**Comment by devaii** [comment]
`apisnoop.cncf.io` does not actually redirect to `apisnoop.cncf.ci`. It's just aliased. 
You can see the path here:

```
~$ host apisnoop.cncf.io 
                                                                                                                                     
apisnoop.cncf.io is an alias for apisnoop.ii.coop.
apisnoop.ii.coop is an alias for apisnoop.cncf.ci.
apisnoop.cncf.ci is an alias for apisnoop.netlify.com.
apisnoop.netlify.com has address 167.99.129.42
apisnoop.netlify.com has IPv6 address 2a03:b0c0:3:d0::d24:5001
```

`apisnoop.cncf.io` has already been set as the "primary domain" for the Netlify project.

![image](https://user-images.githubusercontent.com/44621222/57259123-5b4d6880-7013-11e9-8920-bf5e25cd97ad.png)


What is the requested change? Would you like `apisnoop.cncf.io` to be an alias directly to `apisnoop.netlify.com`? I personally don't have access to DNS records for `cncf.io` or `ii.coop` as I'm sure you are already aware.

**Comment by hh** [comment]
Fix the 301 redirect from https://apisnoop.cncf.io to https://apisnoop.cncf.ci:

It should not redirecty, we want https://apisnoop.cncf.io to be the primary.

![image](https://user-images.githubusercontent.com/31331/57262390-e3894780-70bf-11e9-8ecc-5037ce2745ec.png)

**Comment by hh** [comment]
I tried another browser and it was good.
