### ISSUE TITLE
Prow Jobs Not Running

### ISSUE THREAD

**Issue by devaii** [cncf/apisnoop#234]
# Prow jobs are not running anymore for some reason.

## Short description:
Prow jobs stopped running yesterday. 
Last commit to trigger a job was (9a4bf83)

- Current state:
  -  Prow Jobs are not being triggered automatically
- Desired state:
  - Prow Jobs function as intended: Running from PRs and pushes.
### Tasks:
- [x] [enable debug logging on prow](https://kubernetes.slack.com/archives/CDECRSC5U/p1557254440354800)

**Comment by devaii** [comment]
After some investigation and debugging with @hh we realized that the configmap had some invalid keys.

Particularly here https://github.com/ii/org/commit/24b6430d900440dfa14ff9747d7c132938d636f5#diff-894d802c09cad4857db133aaf9a9f253L51

**Comment by hh** [comment]
We upgraded the prow images, but where still using an old checkconfig command.
Apparently `always_run: true` is no longer valid for postsubmits.
