### ISSUE TITLE
Move header and reset button to sidebar

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#237]
## Short description:

- Current state:
  - Can't see reset button due to size
  - Header takes up room

![image](https://user-images.githubusercontent.com/31331/57397785-8a392980-7221-11e9-8c7c-548bcd7d20b2.png)

- Desired state:
  - Reset button visible, closer to top or within the sidebar
  - move header items to sidebar

### Tasks:
- [ ] Move reset button to sidebar, rename [reset zoom]
- [ ] Move header logo / link to source to sidebar

**Comment by hh** [comment]
Possibly remove some of the white space above the version as well.

**Comment by zachmandeville** [comment]
Implemented in #241 .   We moved the logo to the top of the sidebar, the source code link to the bottom right of the footer, and removed the header.
