### ISSUE TITLE
Add user-agent support to audit-logging

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#24]
Add user-agent to audit-logging:
https://github.com/kubernetes/kubernetes/issues/64791
https://github.com/kubernetes/kubernetes/pull/64812

This should be approved after the code-freeze melts.

**Comment by hh** [comment]
Focused solely on e2e tests and was able to get https://github.com/kubernetes/kubernetes/pull/67550 submitting per test user-agent.

**Comment by hh** [comment]
https://github.com/kubernetes/kubernetes/pull/64812 was merged into [v1.12.0-alpha.1](https://github.com/kubernetes/kubernetes/releases/tag/v1.12.0-alpha.1) !

**Comment by devaii** [comment]
Is this issue ready to be closed now?

**Comment by hh** [comment]
Yes
