### ISSUE TITLE
Netlify previews

### ISSUE THREAD

**Issue by dankohn** [cncf/apisnoop#247]
Could you please enable Netlify deploy previews of PRs.

https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/

**Comment by hh** [comment]
We've had them for a while, but it's taken a bit to integrate them with the prow jobs that generate the underlying data.

Here is a preview of https://github.com/cncf/apisnoop/pull/248

https://deploy-preview-248--apisnoop.netlify.com/?useragents=%5B%5Ee2e.test%5D&showUntested=true&showTested=false&showConformanceTested=false

**Comment by dankohn** [comment]
Great.
