### ISSUE TITLE
Kill the ? in your query parameters

### ISSUE THREAD

**Issue by dankohn** [cncf/apisnoop#251]
Please consider switching from query parameters to just including them in the path to improve SEO and cacheability. See https://www.searchenginejournal.com/url-parameter-handling-seo/290077/#close

The interactive landscape URL scheme is a good model: https://landscape.cncf.io/format=card-mode&grouping=category&category=certified-kubernetes-distribution,certified-kubernetes-hosted,certified-kubernetes-installer,special

Also note that if you change the order of any parameters, it redirects to the canonical ordering, and if you delete a character from any key or value (making it invalid) it deletes that whole parameter. That way, all URLs are canonical.

**Comment by zachmandeville** [comment]
We have followed this advice and mapped the url path to the current section of the sunburst.  For example, this is a sunburst for a particular bucket and job zoomed to stable/core endpoints: http://apisnoop.cncf.io/ci-kubernetes-e2e-gce-cos-k8sbeta-default/1244368729727307776/stable/core
