### ISSUE TITLE
Use github's graphql api to explore PR's on specific Project Boards

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#254]
# Request: 
Given an (org || org/repo) and project board number, what information can we gather from graphql about the board's PR's, and the people, commits, and work those pr's are connected to?

## Short description:
investigatory work for the github graphql api, with the intended goal being an output json snapshot of the pr's on a project board.  We are interested in:
- [x] Who wrote the pr
- [ ] what company are they a part of?
- [ ] what commits are they attached to?
- [ ] what issues are they attached to?
- [ ] what's the status of the pr?
- [ ] how many comments and who is commenting?
- [ ] when was it last updated?

**Comment by hh** [comment]
#261 may help provide insight into what company they are a part of

**Comment by zachmandeville** [comment]
In short, all of the above points can be found through github's api with relative ease.   We found it was best to ping the api from our own application and special api token, as the permissions within the github explorer made it tough to pull data from certain project boards or pull requests, but this was not an issue when doing so from our own app.
