### ISSUE TITLE
Implement a More Flexible Data Storage Method

### ISSUE THREAD

**Issue by devaips** [cncf/apisnoop#255]
# Request: 
Store data in a way which can be queried more flexibly.

## Short description:

- Current state:
  - Data is filtered and queried via redux in the webapp.
- Desired state:
  - Data is able to be filtered/queried in a more general way. eg. SQL
### Tasks:
- [ ] Evaluate options
- [ ] Make architecture changes
- [ ] Make webapp changes.

**Comment by zachmandeville** [comment]
This has been implemented with work around apisnoop v3, and pushing it all into a postgres database.
