### ISSUE TITLE
Add links to Nav Bar for useful initial filters

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#256]

**Comment by devaips** [comment]
**Stable-Core Tested but Not Conformant Filter**

https://apisnoop.cncf.io/?zoomed=category-stable-core&showUntested=false&showConformanceTested=false

**Stable-Core Conformance Tests**

https://apisnoop.cncf.io/?zoomed=category-stable-core&showUntested=false&showConformanceTested=true&showTested=false)

**Comment by hh** [comment]
Thanks @devaips. Looks great.
