### ISSUE TITLE
Look into go guru to figure out test names per PR

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#262]
https://docs.google.com/document/d/1_Y9xCEMj5S-7rv2ooHpZNH15JgRT5iM742gJkw5LtmQ/edit?usp=drivesdk

**Comment by hh** [comment]
This might be interesting to combine https://github.com/cncf/k8s-conformance/pull/622 into an exploration.

**Comment by zachmandeville** [comment]
Closing due to staleness. You can visit current roadmap here: https://github.com/cncf/apisnoop/blob/master/org/roadmap.org
