### ISSUE TITLE
Switch from camelCase to spinal-case in URLs

### ISSUE THREAD

**Issue by dankohn** [cncf/apisnoop#264]
For best practices, see:

https://stackoverflow.com/questions/10302179/hyphen-underscore-or-camelcase-as-word-delimiter-in-uris
https://ux.stackexchange.com/questions/41595/what-is-the-casing-convention-for-url-routes
https://blog.restcase.com/5-basic-rest-api-design-guidelines/

**Comment by hh** [comment]
Advice applied in the last iteration.
Thanks @dankohn

**Comment by Riaankl** [comment]
Thank you, can be closed
