### ISSUE TITLE
Record name of feature_flag for every api schema field

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#270]
# Request: Record name of feature_flag for every api schema field

While not possible to automate `api operations` feature flags, the `api schema.description` field seems contain multiple ways of documentation and the identifying feature flags.

We currently just detect if the description matches one of the 8 string variations.
We could update this to retrieve the feature flag itself.

## Short description:

- Current state:
  - We record a boolean true/false for a schema field that is feature gated
- Desired state:
  - We record a string for the name of the Feature Flag

### Tasks:
- [ ] Update existing ilike queries to pull string from description
- [ ] Update / verify existing reports depending on feature gated boolean value

### Existing boolean feature_flag logic

```sql
CASE
WHEN (   description ilike '%requires the % feature gate to be enabled%'
      or description ilike '%depends on the % feature gate being enabled%'
      or description ilike '%requires the % feature flag to be enabled%'
      or description ilike '%honored if the API server enables the % feature gate%'
      or description ilike '%honored by servers that enable the % feature%'
      or description ilike '%requires enabling % feature gate%'
      or description ilike '%honored by clusters that enables the % feature%'
      or description ilike '%only if the % feature gate is enabled%'
) THEN true
ELSE false
END AS feature_gated,
```

**Comment by hh** [comment]
Would this help to quickly identify all the decorators we need to add?:
 https://docs.google.com/document/d/1wuoSqHkeT51mQQ7dIFhUKrdi3-1wbKrNWeIL4cKb9zU/edit#

/cc @lavalamp

**Comment by lavalamp** [comment]
Definitely not quickly.

**Comment by hh** [comment]
What I hear you saying is it would not be of immediate help because of the current blocking on prioritization and staffing needed for the Field Gate decorator effort.

When the Field Gate flag decorator effort is started, the implementation writers would search the code and possibly only write decorators for newly gated fields rather than use automation from APISnoop to retroactively apply decorators to any existing gated fields.

However this Feature Flag -> schema field data would be helpful for prioritization of which fields to create decorators for.

**Comment by Riaankl** [comment]
Issue Closed: Stale / Clean-up
