### ISSUE TITLE
Rollover endpoint (on outer ring) reveals label/name

### ISSUE THREAD

**Issue by stefandyke** [cncf/apisnoop#28]
Each line on the outer ring of the sunburst visualisation represents an endpoint and when you rollover each available one with your mouse we are showing the name in a box at the top left. However, the name/label box is fixed in place meaning there is a disconnect between the endpoints being rolled over and the information being shown.

In order to make it easier for the user to interrogate each endpoint on the outer ring, when they rollover them a label/name will appear connected to each in closer proximity as per the illustration below.

![endpoint_rollover](https://user-images.githubusercontent.com/42525114/44426911-1815ab80-a5e4-11e8-872d-58081724d6ae.png)

**Comment by zachmandeville** [comment]
Handled now by a summary card that shows to the right of the graph.  This summary card shows the endpoint path and name, whether it's tested, how many tests are run on it, and the test tags on those tests.
