### ISSUE TITLE
Investigate setting persistent urls for the apisnoop services.

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#280]
Apisnoop, when applied to a cluster, spins up a postgres database, a hasura api, and a small web app with some basic statistics.   Each of these are on a port that, to view, you have to run a port-forward for.

It'd be ergonomically pleasant to have them instead set to a custom url for the cluster, like 
`cluster.url/apisnoop` for the webapp and `cluster.url/apisnoop/explorer` for the hasura frontend.

Investigate the work required to do this, and see if the benefit of urls is worth that effort.

**Comment by cjwagner** [comment]
Testing CI integration. Please ignore
/meow

**Comment by cjwagner** [comment]
^Testing CI integration, please ignore.

**Comment by zachmandeville** [comment]
This has been implemented
