### ISSUE TITLE
Website not working on Firefox and Safari

### ISSUE THREAD

**Issue by bartsmykla** [cncf/apisnoop#281]
I tried to open the website, to read more about project today, and it looks like it's broken on Firefox (my daily browser) and Safari. Everything looks fine on Chrome though.
It's showing some content for like a second, and then whole site is becoming white (console visible on the screen).
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/11655498/72788087-790a3e80-3c31-11ea-9b2d-e2d4e65fe9af.png">

**Comment by bartsmykla** [comment]
I will try to investigate a little bit more later, maybe I'll be able to help. :-)

**Comment by bartsmykla** [comment]
Fixed by: https://github.com/cncf/apisnoop/commit/1608fb6110991e74dbec9e9c8e086b60cea2a285

**Comment by hh** [comment]
Thanks for the pair session @bartsmykla
