### ISSUE TITLE
Add Advanced Auditing Webhook Backend Configuration to kops/kubeadm/minikube

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#3]
Advanced Auditing needs a policy file passed to [--audit-policy-file](https://kubernetes.io/docs/reference/generated/kube-apiserver/) to apiserver.

Enabling a webhook also requires configuration file via [--audit-webhook-config-file](https://kubernetes.io/docs/reference/generated/kube-apiserver/)

This ticket is to track support for audit-webhook provisioning:

* Kops: https://github.com/kubernetes/kops/issues/5021
* Kubeadm: https://github.com/kubernetes/kubeadm/issues/759
* Minikube: https://github.com/kubernetes/minikube/issues/2741

**Comment by hh** [comment]
For now we are developing with a kops deployed cluster, and manually logging into the master to update the configuration.

**Comment by dankohn** [comment]
I have a strong preference for kubeadm if it's possible to switch.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by hh** [comment]
Sure thing @dankohn. We will go down that path a bit more today.

**Comment by hh** [comment]
#### WIP: Enable kubeadm to configure auditing webhook:

Notes: https://gist.github.com/hh/9fadc21b2163b252051b5e319c59a80e#audit-webhook-needs

PR: https://github.com/kubernetes/kubernetes/pull/62826

**Comment by hh** [comment]
Ran into some trouble debugging and found it was impossible to increase verbosity "-v" when providing "--config" resulting in a small ticket/pr:

https://github.com/kubernetes/kubeadm/issues/765
https://github.com/kubernetes/kubernetes/pull/62826

**Comment by hh** [comment]
This approach will go away with [dynamic audit webhook configuration](https://github.com/kubernetes/community/pull/2188).
