### ISSUE TITLE
User agent filtering selector

### ISSUE THREAD

**Issue by stefandyke** [cncf/apisnoop#31]
The existing APISnoop implementation illustrates the endpoints accessed by a single app (the e2e conformance tests), however it is possible to capture audit information for all apps that are hitting endpoints and as such we can load this data and then allow it to be filtered by user agent.

Introducing this filter will allow for more in depth data interrogation and provide valuable information to app developers about which endpoints they are hitting and their conformance status (in conjunction with additional visualisation features).

The functionality of the selector is illustrated below:

![user_agent_filtering](https://user-images.githubusercontent.com/42525114/44435231-1dceb980-a603-11e8-852b-23c218a8e15d.png)

**Comment by hh** [comment]
The filtering will be a text field, a dropdown limits us to one at a time.
