### ISSUE TITLE
Tested/untested filtering

### ISSUE THREAD

**Issue by stefandyke** [cncf/apisnoop#32]
When the sunburst visualisation is filtered to show only endpoints accessed by a particular app (besides the E2E test suite) it would be valuable to be able to see which of the accessed endpoints have been tested and which of those haven't.

Combined with volume of hits data this information would provide useful insights as to which endpoints are priorities for conformance testing based on their status and how they are being used.

To that end we need to introduce a selector that allows the sunburst visualisation to be updated based on whether the user wishes to see All endpoints accessed by a particular app, only the Tested endpoints or only the Untested endpoints.

This can be achieved through the addition of a radio button as below:

![tested_untested_filtering](https://user-images.githubusercontent.com/42525114/44435991-dba77700-a606-11e8-8301-caae4ddcb612.png)

**Comment by hh** [comment]
Rather than filtering on tested vs untested, we should only show unhit endpoints when the only useragent is e2e.tests.

We will open another ticket to clarify this.
