### ISSUE TITLE
Overlay - Additional Details

### ISSUE THREAD

**Issue by stefandyke** [cncf/apisnoop#33]
We collect a range of data within the audit logs that can provide further, detailed information about each of the endpoints i.e. what tests are accessing them, who the owners are and what SIGs they belong to.

In addition for the E2E tests we can present more detailed information about each of the tests that are running against the endpoint and their purpose.

All of this information can be presented back to the user when they click on an endpoint from within the sunburst visualisation and to do this we would present an overlay that loads as required. Depending on the available data we can structure the screen in a number of ways - which is being explored.

Illustration below:

![overlay_-_additional_details](https://user-images.githubusercontent.com/42525114/44445734-4fad4380-a636-11e8-9ecf-581b7c9799f8.png)

**Comment by hh** [comment]
This was helpful as a conversation topic, but we may need to revisit when we have and global endpoint+test site that we can tie back to sigs.
