### ISSUE TITLE
+16 endpoints on stable coverage-over-time graph

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#335]
During the last conformance meeting we confirmed 16 endpoints that are not eligible for conformance testing.

- https://github.com/cncf/apisnoop/blob/master/tickets/k8s/EndpointsToNotTest.org

The graph can move the existing stable/conformance line +16 points, and the related percentages.

The existing line can be made a slightly different color, does not need the calculations.

The prologue above can note this change.

/assign @zachmandeville

**Comment by zachmandeville** [comment]
A PR has been opened, https://github.com/cncf/apisnoop/pull/337, that brings in the work necessary to complete this ticket.  

You can find a document of this work here:
https://github.com/cncf/apisnoop/blob/tix_335/tickets/apisnoop/335_plus_16_endpoints_cot_graph.org

**Comment by zachmandeville** [comment]
issue completed with merging of #337
