### ISSUE TITLE
Load Audit Data

### ISSUE THREAD

**Issue by stefandyke** [cncf/apisnoop#34]
To allow others to contribute their audit data to APISnoop, we need to provide an ability to upload audit-logs for analysis. These could then be loaded into the sunburst visualization, or other APISnoop tools allowing for a deeper dive into their own data data.

It might also be possible, once test-infra jobs support storing audit.logs, to use gs://bucket/path/to/audit.log urls as as source.

To allow this I propose a drag/drop if the user wishes to upload a local file or and alternative to input a URL/Link to the data to be consumed by the APISnoop service, as illustrated below:

![load_audit_data](https://user-images.githubusercontent.com/42525114/44445997-4a9cc400-a637-11e8-8a72-9f8e1130aab9.png)

**Comment by devaii** [comment]
This is a good idea. It is currently undecided if we are going to add support for user-submitted audit data at this time. If we do go this route, then there will be a discussion on how to implement this, before we can address the user interface. 

I'm going to keep this open, until there is a decision made on how to go forward.

**Comment by hh** [comment]
This is related to #99, but separating out the running of a dynamic auditsink from importing is important.
Let's focus on creating the auditsink and it's configuration within a targeted cluster first, then come back to having a protocol for loading it into the backend.
