### ISSUE TITLE
Verify both sources of tests run include all conformance tests

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#343]
As part of a pre-submit job we need to automatically review pull requests submitted by a Vendor seeking Kubernetes certification for their product.

There are two checks that need to be carried out to ensure compliance 
1. test results in junit_01.xml must include all required tests for the specified release of Kubernetes.
2. test result logs in the e2e.log file need to show that all tests present in the junit results file are present in the e2e.log file 

Tests required for conformance can be found in the kubernetes/kubernetes repo. Starting from release 1.18 these are present in a YAML file.
https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/conformance.yaml
 
Older versions of the required tests for conformance can be found here TBD

**Comment by olivercodes** [comment]
Working of this pr - https://github.com/cncf-infra/prow-config/pull/6/files

**Comment by bernokl** [comment]
1) Create list of URL's based on version
2) Create map based on conformance.yaml/txt we get from the appropriate item we fetch from the list above
3) Create map of tests ran based on e2e.log
4) Diff the two lists
5) Report on diff
6) Repeat 3,4,5 for junit_01.xml

**Comment by bernokl** [comment]
After discussion we decided to exchange this, for generating conformance.yaml for all the older versions. we will keep them in the conformance/doc directory of our repo 
- [x] Generate list of conformance test from https://github.com/kubernetes/kubernetes/blob/release-1.17/test/conformance/testdata/conformance.txt
  - for versions of k8s 1.15-1.17

**Comment by hh** [comment]
Let's be sure to get this data back far enough to create a PR to fix missing **version: ""** metadata (in the test/code comments) for **[Conformance]** tagged tests.

https://github.com/kubernetes/kubernetes/issues/92273#issuecomment-651969139

**Comment by Riaankl** [comment]
conformance.yaml meta data updated by #93487
conformance.yaml for 1.16-1.18 created manually for Conformance gate.
/close
