### ISSUE TITLE
Tool to generate a list of tests required for each PRs version:

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#344]
Tooling to generate a list of tests that are still considered conformance from each release by filtering out tests for newer releases:

-  [x] master https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/conformance.yaml

**Comment by bernokl** [comment]
Next steps:
- Create list of URL's based on version
- Create map based on conformance.yaml/txt we get from the appropriate item we fetch from the list above
- Create map of tests ran based on e2e.log
- Diff the two lists
- Report on diff

**Comment by bernokl** [comment]
This is now a function that loads conformance.yaml into a map. The process works for v1.18, however the labels for at least a few tests changed, making conformance.yaml v1.18/master not backwards compatible with v1.17, the example is this test in v1.18 conformance.yaml:
'[k8s.io] [sig-node] NoExecuteTaintManager Multiple Pods [Serial] evicts pods with minTolerationSeconds [Disruptive] [Conformance]'

has the following name in v1.17/junit_01.xml:
[sig-scheduling] NoExecuteTaintManager Single Pod [Serial] removing taint cancels eviction [Disruptive] [Conformance]

my proposal is to generate conformance.yaml_v1.17 using the same tool we used to generate v1.18

**Comment by hh** [comment]
Done, thanks @bernokl !
