### ISSUE TITLE
Broken links in docs/test-writing.org

### ISSUE THREAD

**Issue by haardikdharma10** [cncf/apisnoop#350]
In the file 'test-writing.org' three links, specifically **"Setting up Kubemacs with APISnoop"** , **"SQL Tips and Tricks"**  and **" Anatomy of our Go function"** are broken. When trying to change them, the confusion is that they are not linked to any link in the .org file as shown in the screenshot below:

<img width="409" alt="Screenshot 2020-05-26 at 3 50 00 PM" src="https://user-images.githubusercontent.com/53044263/82889681-bdec0c00-9f68-11ea-9a1e-f91ba6df17c4.png">

**Comment by Riaankl** [comment]
/assign @zachmandeville 
Please see comment on broken links for doc/test-writing.org
I also APISnoop/test-writing.org have under the same file name other valuable information.  Please review the location and name.

**Comment by Riaankl** [comment]
/close
Fixed by PR: Fix broken link #349
