### ISSUE TITLE
Update and improve APISnoop graphical data display

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#359]
# Update graphical presentation of API Conformance data

## **Apisnoop.cncf.io**
Break APISnoop into 3 pages:
-   [X]  1. Page 1 Sunbust top of the page + Explanation + Link to Page 2: Progress over time
-   [X]  2. Page 2: Progress over time move to page 2
-   [x]  3. ii History page, not part of  APISnoop (As a static infographic)

- [X] @hh: Ping @Liggitt & community on Slack on their thoughts and what they would gain out of the improvements.

## **APISnoop Progress reports**
Page 2:
-   [X] 1. Stable Endpoint Coverage Over Time - In real numbers
-   [x] 2. Stable Endpoint Coverage Over Time - In % (Scale =100%)
-   [X] 3. New endpoints per release and their current coverage graph
-   [x] Make "Still untested" a negative graph, below the X-Axis if possible. (Technical Debt below the x Axis)

**Comment by zachmandeville** [comment]
I've made a progress percentage chart and aded it to the conformance-progress page, with a preview available here:
https://snoop-app-git-performance-progress.iinz.vercel.app/conformance-progress#conformance-progress-percentage

I have not merged it yet, as there's a discrepancy in coverage for 1.18 that I want to look into.  When that is discrepancy is removed, I'll feel good to merge it in.

**Comment by hh** [comment]
Can we update "From this release" to "From each release": 
<img width="227" alt="image" src="https://user-images.githubusercontent.com/31331/86969850-86f15300-c1c2-11ea-82cd-edf5078f395b.png">

**Comment by Riaankl** [comment]
APISnoop Updated with all changes proposed in the issue.
/close
