### ISSUE TITLE
Resolve Conformance Tested Endpoints that show as Untested in APISnoop

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#362]
### Description of the Issue:
PR [#89753](https://github.com/kubernetes/kubernetes/pull/89753) Merged a Conformance test for 5 x NamespacedEvent Endpoints. 
Issue [#86288](https://github.com/kubernetes/kubernetes/issues/86288) and PR [#89753](https://github.com/kubernetes/kubernetes/pull/89753) showed that the endpoints will be covered by the proposed test.
It was discovered that the Endpoints are not covered by conformance tests.

### Endpoint list:
listCoreV1EventForAllNamespaces
readCoreV1NamespacedEvent
patchCoreV1NamespacedEvent
deleteCoreV1NamespacedEvent
createCoreV1NamespacedEvent

### Initial discovery:
- The Endpoints showed up in the mock test template query as untested. 
- The Endpoints was targeted for conformance testing, when it was discovered that they should be cover by PR#89753
- The Endpoints was checked against the [APISnoop](https://apisnoop.cncf.io/) website, where they also showed "Untested" with "No Conformance Tests".

### Target outcome for this issue:
**Step** 1:
- [ ] Determine the technical reason why the Endpoints are not shown as conformant in APISnoop in spite of PR #89753 being merged
- [ ] Determine how to correct the failure and get the Endpoints to show as conformant 
- [ ] Assign the task for correction or create an Issue in K/K if it require SIG Architecture intervention 

**Step** 2:
- [ ] Determine if this failure mode could affect other Endpoints that have valid conformance tests and still show up as untested
- [ ] If applicable, list affected Endpoints and correct the conformance status conflict.

**Comment by Riaankl** [comment]
![image](https://user-images.githubusercontent.com/61125752/89471609-b2bc2480-d7d2-11ea-86fd-02b669ae4273.png)
More endpoints was identified the was Promoted to conformance and is not showing as conformance tests in SnoopDB or APISnoop

**Comment by Riaankl** [comment]
Meta data update, endpoints does not show up in APISnoop yet.

**Comment by hh** [comment]
https://apisnoop.cncf.io/conformance-progress/endpoints/1.20.0?filter=old-covered-by-new
![image](https://user-images.githubusercontent.com/31331/97222370-2cdcd200-1833-11eb-9926-ba27175a4e78.png)

We now shows those missing endpoints! Great work!

**Comment by Riaankl** [comment]
We are still missing: 
deleteCoreV1CollectionNamespacedEvent
listCoreV1NamespacedEvent

**Comment by hh** [comment]
ok, leaving this open.

**Comment by zachmandeville** [comment]
These two endpoints now show as tested, after increasing the test runs we pull our logs from:
- [deleteCoreV1CollectionNamespacedEvent](https://apisnoop.cncf.io/1.21.0/stable/core/deleteCoreV1CollectionNamespacedEvent)
- [listCoreV1NamespacedEvent](https://apisnoop.cncf.io/1.21.0/stable/core/listCoreV1NamespacedEvent)

Are we good to close this, @Riaankl ?

**Comment by Riaankl** [comment]
I was adding it to my list of this to revisit this week and check.
Thanks for beating me to it.
/close
