### ISSUE TITLE
Endpoint promoted from Beta to Stable, showing up as untested in APISnoop

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#363]
### **Description of the Issue:**
During the update of the APISnoop website it have been discovers that one endpoint in release 1.19 show up as newly introduced to stable without a conformance test. 

### **Endpoint list:**
readNetworkingV1NamespacedIngressStatus

### **Initial discovery:**
- Several Ingress endpoints where promoted by [PR #89778](https://github.com/kubernetes/kubernetes/pull/89778) 17 June 2020 from Beta to Stable
- [PR #91996](https://github.com/kubernetes/kubernetes/pull/91996) promote the conformance tests for the Ingress endpoints
- The test can be found [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/ingress.go#L943-L1161)

### **Target outcome for this issue:**
Determine if:
- [x] The endpoint was promoted, but not covered by the test
- [x] The endpoint is covered by the test but there is an issue in how the audit events are being gathered.

****Proposed** Initial steps**
Bring the issue under the attention of the owners of PR #89778 & #91996 for feedback.

**Comment by zachmandeville** [comment]
have reached out to see if this test should have covered the endpoint and it's not being picked up in the audit logs, or if it truly just snuck in.  Will update this ticket based on ensuing conversation.

**Comment by Riaankl** [comment]
The endpoint was missed in the Promotion PR from Liggitt's team.
Fixed by @heyste in #93038
/close
