### ISSUE TITLE
Recording Conformance hits after the depreciation of Dynamic Auditing Configuration API

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#364]
### **Description of the Issue:**
 28 May SIG Auth leads have decided to remove the existing alpha implementation of [dynamic audit](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/0014-dynamic-audit-configuration.md) since it does not have a clear path to GA with broad enablement, and has not made any meaningful progress in the last 1.5 years.
The depreciation is done via K/K PR [#91502](https://github.com/kubernetes/kubernetes/pull/91502)

The removal will affect the functioning of APISnoop.

### **Endpoint list:**
Dynamic Audit Configuration

### **Initial discovery:**
Was brought up in [SIG Auth mailing list](https://groups.google.com/forum/#!topic/kubernetes-sig-auth/aV_nXpa5uWU), PR [#91502](https://github.com/kubernetes/kubernetes/pull/91502) and discussed in SIG Arch Office hours meeting on [2 June 2020](https://docs.google.com/document/d/1W31nXh9RYAb_VaYkwuPLd1hFxuRX3iU0DmaQ4lkCsX8/edit?pli=1#heading=h.bdqgpg5gl8r)

### **Target outcome for this issue:**
Find an alternative solution to replace the interaction of Dynamic Audit Configuration with APISnoop.

**Comment by hh** [comment]
We have updated our approach to configuring apiserver within kind, Minikube, and cluster-api.
Nice work everyone!
