### ISSUE TITLE
Improve visual focus in APISnoop on New endpoints promoted without tests and Old endpoints covered by new tests 

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#371]
### **Description of the Issue:**
To better highlight the work done to remove old technical debt and ensure no new technical debt is incurred more, contrasting colours should be used.

### **Proposed change:**
Change "New endpoints promoted without tests" to bright yellow 
Change "Old endpoints covered by new tests" to dark blue

### **Target outcome for this issue:**
Improve focus on removal of technical debt

### **Visual mock-up:**
![image](https://user-images.githubusercontent.com/61125752/89475175-9d97c380-d7db-11ea-9009-819631b7db6a.png)

**Comment by hh** [comment]
The inprogress branch / deploy:

https://apisnoop-git-stateful-urls.ii-nz.vercel.app/conformance-progress

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/31331/90696447-60016300-e2d0-11ea-8b1f-f40e3ce62557.png">

**Comment by zachmandeville** [comment]
adjusted the colours so that blue represents progress toward technical debt.
implemented in https://github.com/apisnoop/snoopApp/pull/23.
