### ISSUE TITLE
Improve legend description for "Stable Endpoint Coverage At Time of Release" graph

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#372]
### **Description of the Issue:**
End users might not find the [graph](https://apisnoop.cncf.io/conformance-progress) legend descriptive enough.

### **Proposed change:**
Add a description to every entry:
- New endpoints promoted with tests (regular new development)
- New endpoints promoted without tests (this should not happen)
- Old endpoints covered by new tests (paying off technical debt)
- Tested (past regular development) 
- Untested (technical debt)

### **Target outcome for this issue:**
Improve user's understanding of the graph

**Comment by zachmandeville** [comment]
implemented in https://github.com/apisnoop/snoopApp/pull/23
