### ISSUE TITLE
Make the number/percentage toggle stateful in the URL for "Stable Endpoint Coverage At Time of Release" graph

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#373]
### **Description of the Issue:**
The number/percentage graphs can not be linked in documents to show the desired view if the options is not linked to stateful ULR's

### **Proposed change:**
Update to Stateful URL's
https://apisnoop.cncf.io/conformance-progress/number
https://apisnoop.cncf.io/conformance-progress/percentage

### **Target outcome for this issue:**
Allow either graph to be referenced in external documentation.

**Comment by zachmandeville** [comment]
Have implemented this in a branch of apisnoop, viewable here:
https://apisnoop-git-stateful-urls.ii-nz.vercel.app/conformance-progress?stablechart=number&relchart=percentage

it is part of [SnoopApp PR 23](https://github.com/apisnoop/snoopApp/pull/23)

If this behaviour, and the url's, look good then we can merge it in.

**Comment by zachmandeville** [comment]
https://github.com/apisnoop/snoopApp/pull/23 is merged.  We can close this ticket.
