### ISSUE TITLE
Add a list of Endpoints considered not eligible for conformance to the APISnoop web page

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#374]
### **Description of the Issue:**
At the end of 1.19 there was 485 stable Endpoints showing in the sunburst and only 427 is accounted for in the "Stable Endpoint Coverage At Time of Release" graph. This is likely all represented by endpoints not eligible for conformance.

### **Proposed change:**
Add a list of endpoints not eligible for conformance to ensure:
- the data make sense to users and there on "gaps" in the numbers
- having the list of "endpoints not eligible for conformance" would create community awareness of the topic. It was raised in meeting and Slack with no feedback.

### **Target outcome for this issue:**
Improved user experience and community awareness of "endpoints not eligible for conformance"

**Comment by zachmandeville** [comment]
I've added a list of ineligible endpoints, and the reason they are ineligible, to our conformance progress page.

It is reachable through a link in that page's introductory text, or directly at: https://apisnoop.cncf.io/conformance-progress/ineligible-endpoints
