### ISSUE TITLE
Setup Prow for APISnoop

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#38]
```cucumber
As a APISnoop developer
I want to be able to utilize the CI infrastructure provided by k8s.io
And populate the GCS buckets used by test-grid and APISnoop
In order to innovate on the type of k8s conformance data available to our community

Given our repo
When we submit a PR
Then we should trigger the prow plugins configured for our repo
```

We'll document this as we go, so we can ensure others can do the same. The person currently on k8s oncall can be found at:  https://go.k8s.io/oncall

- [x] [Grant k8s-ci-robot owner (admin?) level](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started.md#bot-account) access to the Github orgs that prow will operate on
- [x] Ask k8s oncall to accept the invitation for k8s-ci-robot to be a collaborator
- [x] Add k8s oncall as an admin to your repo to allow them to setup HMAC + webhook
- [x] [Ask k8s oncall to configure a webhook to your github org](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started.md#add-the-webhook-to-github) pointing to https://prow.k8s.io/hook, content type to application/json including the HMAC
- [x] Submit a PR against https://github.com/kubernetes/test-infra enabling prow/plugins.yaml by adding this repo
- [x] Verify k8s oncall has accepted the invitation for k8s-ci-robot to be an admin
- [x] Verify webhook has been configured, and that events are flowing
- [x] Verify plugin works (/cat and /dog are fine)

**Comment by hh** [comment]
@amwat would you mind sending me the HMAC we need to configure the webhook?

**Comment by hh** [comment]
I was able to add @k8s-ci-robot as an admin, but not an owner. We'll see if that is enough permissions. (and the invitation was accepted)

**Comment by amwat** [comment]
Additionally, could you also add me as an admin so that I can setup the HMAC for you?

**Comment by hh** [comment]
https://github.com/cncf/apisnoop/invitations should show an Admin invite for you @amwat

**Comment by hh** [comment]
Verifying that webhook is configured:

![image](https://user-images.githubusercontent.com/31331/45981270-8b5d8200-c0a8-11e8-9f23-c6537aad1579.png)

Verify that events are flowing:

![image](https://user-images.githubusercontent.com/31331/45981296-a03a1580-c0a8-11e8-87d1-d481f5732b11.png)

**Comment by hh** [comment]
Verify that k8s-ci-robot has been added as an admin:

![image](https://user-images.githubusercontent.com/31331/45981426-0aeb5100-c0a9-11e8-8832-50d022a299d2.png)

**Comment by hh** [comment]
Testing
/cat

Testing
/dog

**Comment by hh** [comment]
Testing:
/meow

**Comment by hh** [comment]
Testing:
/woof

**Comment by hh** [comment]
Thanks @amwat !
