### ISSUE TITLE
Document kind/minikube/clusterapi deployment of APISnoop DB+Auditsink

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#384]
Much of our deployment processes are within humacs, but it would be good to have a simple set of scripts to deploy the auditsink + snoopdb within a cluster configured to point at it via:

- kind
- minikube
- clusterapi

**Comment by hh** [comment]
We all use this daily via clusterapi:
- https://github.com/humacs/humacs/blob/main/infra/cluster-api/cluster-setup.sh
For kind:
- https://github.com/cncf/apisnoop/tree/master/kind#setup
And finally Minikube:
- https://github.com/cncf/apisnoop/blob/bbf24533f4762eb484452eba9386999d574ab61f/org/minikube%2Bauditsink.org#start

I think pulling these together in some documentation would be useful, maybe as part of our kubecon talk deep-dive.

**Comment by Riaankl** [comment]
This is not ralevent to our current way of working with SnoopDB.
