### ISSUE TITLE
Update SnoopDB Readme.md with user and developer instructions

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#391]
The current in [Readme.md](https://github.com/cncf/apisnoohttps://github.com/kubernetes/kubernetes/pull/95128#issuecomment-700957913p/blob/master/apps/snoopdb/README.md#snoopdb) requier cloning the repo, which target developers.

Please add alternative options for users that do not which to clone the complete repository.

**Comment by zachmandeville** [comment]
README updated at https://github.com/cncf/apisnoop/tree/master/apps/snoopdb
