### ISSUE TITLE
Automate Updates using GCB + Prow

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#399]
## Summary

Improve the way we update apisnoop from a manual, opaque process to an automated, transparent process.  For automation, we can use a combination of google cloud build(GCB), prow, and github PR's to reduce human labour and build a browsable history of coverage changes.

## Background

In the cncf/apisnoop repo is a directory called [resources/coverage](https://github.com/cncf/apisnoop/tree/master/resources/coverage) that holds a number of json files detailing coverage info for individual releases and our overall conformance progress.  The site https://apisnoop.cncf.io consumes these JSON files and visualizes the data.  So when you update the coverage files, the site updates automatically.

The process to update the json is as follows:
- clone down this apisnoop repo
- get a snoopdb instance running, forwarded to port 5432 (see its [README](https://github.com/cncf/apisnoop/blob/master/apps/snoopdb/README.md))
- from the root of the apisnoop repo run:
```shell
psql -U postgres -d postgres -h localhost -f apps/snoopdb/postgres/generate-json.sql
```
This will run though some sql operations to get the coverage details from this fresh snoopdb instance and output it to our resources folder.

Currently, all this is done manually.  Any automated process will need to be able to interact with a running snoopDB database, write files to the apisnoop repo, and commit these changes.

## Using GCB and Prow

We can extend how we are using GCB in apisnoop to do the updating of our json.  We would add a github secret to our GCB settings, then use a prow job, run daily, that goes through a GCB process of building and running our snoopdb image, updating the json, and then using our secret to push to a branch in the apisnoop repo.

By running this as a periodic prow job and using GCB's secret manager, we won't need to request any addtiional config changes to the k8s prow instance and the admin side would go down.  

## Our PR's

We would want to open a PR when there's been any change to coverage.  We could do this simply by seeing if there's been any changes, apart from updated-date, to the generated files.

These changes could include:
- new endpoints
- new tests
- changes in test descriptions
- changes in endpoint details
- changes in tests that cause them to hit more endpoints

Some of these changes we'd want to signal to the release team, as it could impact the release of k8s next version (namely, if new endpoints are promoted to GA without any conformance tests).  Other changes are interesting, but don't affect a release (e.g. a change in a test description, or new alpha endpoints).

If Any change, trivial or non-trivial, occur, we'd want the process to open a new PR in our repo.  We can then review and merge this PR.  The site could now have a more meaniongful 'updated on' section, that includes a link to the PR that triggered the update.  

In addition, if there's a non-trivial change to the conformance coverage, we would want to send these PR details to sig-conformance and sig-release, 

This method would allow us to

**Comment by Riaankl** [comment]
Auto update of APISnoop via Github actions is working.
This issue can be closed
