### ISSUE TITLE
Create a prow jobs for APISnoop

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#41]
```cucumber
As an APISnoop contributor
I want to be able to create artifacts for test-grid / gcs
In order to provide interesting changes to data sets

Given a new style of data generation
When I create a new prow job for APISnoop
And it includes new forms of data (related to conformance)
Then it will be available for everyone to access
And perform their own analysis
```

**Comment by hh** [comment]
Closing for now.

**Comment by hh** [comment]
I'd like to revisit using prow to auto-generate apisnoop data into our GCS bucket using prow jobs.
Will discuss with @spiffxp

**Comment by hh** [comment]
#38 has the walkthru for our initial configuration.
We still need to find the right cluster.

**Comment by hh** [comment]
We are currently using our own cluster.
We have presubmit jobs working for PRs:

https://github.com/ii/org/blob/master/cncf/ci/prow.org#presubmits

However, we still need to complete updating the postsubmit job to publish to a known gcs bucket prefix that the netlify production/master build and deploy script can pick up.

I suggest we bring that configuration into our repo using a [netlify.toml](https://www.netlify.com/docs/netlify-toml-reference/#getting-started) so it's clear what's running on PRs vs on commits / merges to master.

**Comment by hh** [comment]
/assign @devaii 
The prow jobs are created, ensure the documentation is sufficient for you and that changes to netlify.toml and ./hack/ci/{netlify,prow}-{pr,production.sh work as expected based on these jobs.

**Comment by devaii** [comment]
/lgtm

Made a small update to `netlify-production.sh` with @zachmandeville to get a working bucket path.

**Comment by devaii** [comment]
See da67125b12266f430d4817798f4428455aa402ee
