### ISSUE TITLE
Marking NodeProxy endpoints as Ineligible for Conformance

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#422]
### **Description of the Issue:**
As per [#95930](https://github.com/kubernetes/kubernetes/issues/95930) Nodeproxy endpoints are Ineligible for Conformance

### **Endpoint list:**
|               endpoint                |               path                |       kind       |
|---------------------------------------|-----------------------------------|------------------|
| connectCoreV1PutNodeProxyWithPath     | /api/v1/nodes/{name}/proxy/{path} | NodeProxyOptions |
| connectCoreV1PutNodeProxy             | /api/v1/nodes/{name}/proxy        | NodeProxyOptions |
| connectCoreV1PostNodeProxyWithPath    | /api/v1/nodes/{name}/proxy/{path} | NodeProxyOptions |
| connectCoreV1PostNodeProxy            | /api/v1/nodes/{name}/proxy        | NodeProxyOptions |
| connectCoreV1PatchNodeProxyWithPath   | /api/v1/nodes/{name}/proxy/{path} | NodeProxyOptions |
| connectCoreV1PatchNodeProxy           | /api/v1/nodes/{name}/proxy        | NodeProxyOptions |
| connectCoreV1OptionsNodeProxyWithPath | /api/v1/nodes/{name}/proxy/{path} | NodeProxyOptions |
| connectCoreV1OptionsNodeProxy         | /api/v1/nodes/{name}/proxy        | NodeProxyOptions |
| connectCoreV1HeadNodeProxyWithPath    | /api/v1/nodes/{name}/proxy/{path} | NodeProxyOptions |
| connectCoreV1HeadNodeProxy            | /api/v1/nodes/{name}/proxy        | NodeProxyOptions |
| connectCoreV1GetNodeProxy             | /api/v1/nodes/{name}/proxy        | NodeProxyOptions |
| connectCoreV1DeleteNodeProxyWithPath  | /api/v1/nodes/{name}/proxy/{path} | NodeProxyOptions | 
| connectCoreV1DeleteNodeProxy          | /api/v1/nodes/{name}/proxy        | NodeProxyOptions |

### **Communication with the community:**
"In the Conformance office hour meeting of 20 October 2020 the NodeProxy endpoints was discussed. 13 Node Proxy endpoints can not be Conformance tested as explained in this issue:
NodeProxy endpoints can not be Conformance tested in their current state #95930

The topic was taken to the SIG Node meeting 7 Oct 2020 where it was said that the NodeProxy endpoints would likely be deprecated and not updated to make them eligible for conformance testing. The endpoints where introduced in 1.5 and the original purpose the endpoints was intended for is not valid any more.

Therefore we think it should make sense to mark them as 'Ineligible for conformance' in APISnoop and refer to the Issue #95930. Should the endpoints be updated later, they could be brought back for Conformance testing.

If no one object to the proposal we will mark them as as 'Ineligible for conformance' before 1.20 test freeze."

Communicated via #SIG Architecture on the mailing list, [K8s Conformance slack](https://kubernetes.slack.com/archives/C78F00H99/p1604441714090900) and [SIG Node Slack](https://kubernetes.slack.com/archives/C0BP8PW9G/p1604513805439000) with no oposition to the proposed move of the endpoint to Ineligibility.

### **Target outcome for this issue:**
Mark the NodeProxy endpoints as Ineligible for Conformance

**Comment by zachmandeville** [comment]
These are now marked as ineligible with 'unable  to be tested, likely soon deprecated' as the reason

**Comment by Riaankl** [comment]
NodeProxy Endpoints refer incorrectly to [#96206](https://github.com/kubernetes/kubernetes/pull/96206)
Please update to refer to [#95930](https://github.com/kubernetes/kubernetes/issues/95930)
/cc @zachmandeville

**Comment by Riaankl** [comment]
Updated and working Thank you @zachmandeville
