### ISSUE TITLE
Marking ServiceAccountIssuerOpenID as Ineligible for Conformance due to being Beta Endpoints 

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#428]
### **Description of the Issue:**
ServiceAccountIssuerOpenID are new Beta endpoints currently showing as new technical debt of 1.20 in APISnoop.
There meta data still need updating to show their Beta status.

### **Endpoint list:**
Endpoint | Level | Category | 
-- | -- | -- | 
getServiceAccountIssuerOpenIDConfiguration | stable | WellKnown |   |  
getServiceAccountIssuerOpenIDKeyset | stable | openid

### **Community interaction:**
[#96206](https://github.com/kubernetes/kubernetes/pull/96206) aim to add "Beta" tag to meta data.
However this update is likely not going to be ready by end of 1.20.
Therefor the endpoints would show a new technical debt.

### **Target outcome for this issue:**
Mark the ServiceAccountIssuerOpenID endpoints as Ineligible for Conformance. In order to not show a false positive for "new technical debt"

**Comment by zachmandeville** [comment]
These endpoints are now designated as 'beta' in apisnoop, and so will nto show up in the conformance coverage yet.

I will keep an eye on that PR and update our logic when there's beta metadata to check.
