### ISSUE TITLE
Marking Ephemeralcontainers endpoints as ineligible for conformance

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#456]
### **Description of the Issue:**
Ephemeralcontainers endpoints were promoted with [#97276](https://github.com/kubernetes/kubernetes/pull/97276) to support Alpha endpoints.

### **Endpoint list:**
| Endpoint | 
|-- | 
|patchCoreV1NamespacedPodEphemeralcontainers	|
|readCoreV1NamespacedPodEphemeralcontainers|
|replaceCoreV1NamespacedPodEphemeralcontainers|

### **Community interaction:**
The topic was discussed and agreed in the January 26, 2021Conformance Office Hours Meeting 

### **Target outcome for this issue:**
Mark the endpoints as Ineligible for Conformance. In order to not show a false positive for "new technical debt"

**Comment by zachmandeville** [comment]
I've added them to our ineligible list, and linked them to #97276 .  You can see the updated graphs now at apisnoop.cncf.io/conformance-progress

**Comment by Riaankl** [comment]
Thank you @zachmandeville
