### ISSUE TITLE
Move the tracking of Ineligible  endpoints to K/K repo to make the tracking a community effort via pull requests

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#457]
### **Description of the Issue:**
Currently, APISnoop list of ineligible endpoints is owned and managed exclusively by ii.coop.
To make the process more transparent and community-owned the list would be moved to the k/k repo under [testdata](https://github.com/kubernetes/kubernetes/tree/master/test/conformance/testdata) in the form of a .yaml file.

### **Community interaction:**
The topic was discussed and the January 26, 2021Conformance Office Hours Meeting and referred to the SIG Architecture meeting on January 28, 2021.
The SIG Architecture meeting attendees agreed on this proposed change.

### **Target outcome for this issue:**
- Copy Ineligible endpoints data from APISnoop to ineligible_enpoints.yaml under [k/k testdata](https://github.com/kubernetes/kubernetes/tree/master/test/conformance/testdata)
- All future adding and removing of endpoints to the list will be done via pull requests. 
- The ineligible endpoints list in APISnoop is generated by consuming the ineligible_enpoints.yaml for k/k.

**Comment by Riaankl** [comment]
add ineligible_endpoints.yaml [#98677](https://github.com/kubernetes/kubernetes/pull/98677) created by @zachmandeville and added to Conformance meeting agenda and Slack channel for approval.

**Comment by Riaankl** [comment]
@zachmandeville the release for 1.21 is closed. Can you please update APISnoop to pull from the `ineligible_endpoints.yaml` file?

**Comment by zachmandeville** [comment]
implemented in #499
