### ISSUE TITLE
apisnoop.cncf.io shows meaningful loading information upon first visiting site

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#50]
When I visit the website, it will take a moment for the javascript to load, and then for all the graphs and data to appear.  During this load time, I should still see something on the screen so I know the page loaded correctly, and now we are just loading the app.  In other words, a loading screen that is rendered in static html, that is then replaced by the javascript-enabled visualizations.

**Comment by devaii** [comment]
Implemented in 27d104be08a5e332a7a6730ad221edc4a43564ee
