### ISSUE TITLE
Switching to different releases 

### ISSUE THREAD

**Issue by heyste** [cncf/apisnoop#506]
**What did you expect to happen?**

After clicking on the `switch release` button the site should display a list of releases to choose from 1.15 to the current release.

**What actually happened?**

The site is displaying multiple links for 1.15 release when using either Chrome or Firefox other than the order of the links.

![apisnoop-switch-releases-firefox](https://user-images.githubusercontent.com/1710179/118899272-8a1caa00-b962-11eb-871f-c2641fe2fedd.png)
- Chrome 90.0.4430.212
- Firefox 88.0.1

Getting similar results when using either Ubuntu or Mac OS.

**Comment by heyste** [comment]
Using either "private" or "incongnito" window don't seem to give a common display of the links.

**Comment by zachmandeville** [comment]
This was fixed in https://github.com/cncf/apisnoop/pull/508
