### ISSUE TITLE
APISnoop Sunburst Graph error related to `Only show conformance eligible endpoints` function

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#507]
**What did you expect to happen?**
When opening APISnoop and selecting the ` Only show conformance eligible endpoints` option this is expected:
![image](https://user-images.githubusercontent.com/61125752/118901659-f0f09200-b967-11eb-9db7-6e7548d8ad96.png)

**What actually happened?**
![image](https://user-images.githubusercontent.com/61125752/118901683-02399e80-b968-11eb-9b3e-5a5336a65ddc.png)

- The image seems to be a mix of Alpha / Beta / Stable without `ineligible endpoint.

- The bug was experienced by @hh and @Riaankl 

- Once changing the view by selecting `Stable` and then ` Only show conformance eligible endpoints` it is not possible to repeat the behavior. Possible due to caching page?

**Comment by zachmandeville** [comment]
Fixed in https://github.com/cncf/apisnoop/pull/511
