### ISSUE TITLE
bottom margin added to sunburst section, to provide more space between it and footer

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#52]
When I visit the page for the first time, without setting any additional filters, the sunburst section is sometimes cut off by the footer.  Adding a margin to the bottom of our sunburst section would provide necessary spacing.

**Comment by devaii** [comment]
The sunburst is still getting cut-off for me. I am not very familiar with tachyons css, but it looks to me like there needs to be the equivalent of a `position: relative` element added to that section.

**Comment by zachmandeville** [comment]
This issue was about giving a margin to the sunburst section so that the footer does not cut off any part of the sunburst.   We have now fixed this interaction.  Having discussed this mroe with you, I understand that you are talking about having the sunburst show totally on your page upon the inital load, and not have to scroll down to see it.  The scrolling down to see was a design decision of mine, as I wanted each section to have good whitespace.  I am down to discuss and change the layout, but it feels separate from the initial goal of this ticket.

**Comment by devaii** [comment]
That makes sense, and I agree; I will create another issue to discuss changing the initial page layout. Thanks!
