### ISSUE TITLE
Consistent positioning and alignment of sections from top to bottom of page.

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#54]
When I visit the site, I want it to be aesthetically pleasing.  There is dissonance currently where some sections are given a lot of white space, and some are not given any at all.  It  is okay for the site to have new amounts of padding, but it should be consistent and intentional.  

Give an audit to the site to make sure we have a set centering and spacing for all elements, to give visual consistency to the page.

**Comment by zachmandeville** [comment]
#59

**Comment by devaii** [comment]
Alignment fixed in e19bf9aceb177e3cf455102ffe33f2e51c339f01
