### ISSUE TITLE
Move to CNCF Prow instance instead of Kubernetes's Prow Instance

### ISSUE THREAD

**Issue by BenTheElder** [cncf/apisnoop#548]
xref: https://github.com/kubernetes/test-infra/issues/12863

**Comment by hh** [comment]
Our two cncf/apisnoop jobs focus is #sig-arch and #sig-release and the paying down of technical debt for the Kubernetes community. Anything related to cncf/k8s-conformance / cncf.io/ck is already running on prow.cncf.io.

xref: https://github.com/kubernetes/test-infra/issues/12863#issuecomment-1139144446

**Comment by BenTheElder** [comment]
I'm not talking about the apisnoop jobs in particular, this repo's automation is prow.k8s.io based entirely AFAICT
<img width="1471" alt="Screen Shot 2022-05-26 at 4 38 06 PM" src="https://user-images.githubusercontent.com/917931/170598446-16a88c4b-8696-44fa-9c56-a7cc7ba01319.png">


https://github.com/cncf/apisnoop/pull/550#event-6656694138

k8s-ci-robot is the prow.k8s.io bot account
