### ISSUE TITLE
When you click on an endpoint, it has a different interaction and visual appereaance than clicking and zooming into level or category

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#55]
Currently, when you click on a level or category, it 'zooms' into that section, where the section becomes the entire ring.  When you click on an endpoint, it does the same thing.  This behavior gives a nice appearance for level/category, but looks strange when zoomed to level/category/endpoint.  A better interaction would be that the level/category zoom in, but the endpoint just locks into place.  

[[screenshots go here]]

**Comment by devaii** [comment]
Implemented this interaction improvement in commit cc94b83f436003bb3ec60f81579548705b937bfe
