### ISSUE TITLE
Test Href's load the test id, and not just '${test[test_item_id]}

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#57]
When you click on an individual test, you can see the url change, but it shows as #{test[test_item]}.  This is the variable, instead of the value of the variable.  This should change to the actual value.

**Comment by zachmandeville** [comment]
The issue was that all the test links needed to have a href tag, but there was no real page they were going to.  My current fix was changing them to be button elements, and clicking the button shows their sequence.  They look the same, but are semantically different, and now do not need a dummy href link.  With this change, this issue is moot.

**Comment by devaii** [comment]
> The issue was that all the test links needed to have a href tag, but there was no real page they were going to. My current fix was changing them to be button elements, and clicking the button shows their sequence. They look the same, but are semantically different, and now do not need a dummy href link. With this change, this issue is moot.

Implemented in commit: 58a9168c54df2e753fe6880d4de060054756b166
