### ISSUE TITLE
Enhancement: SnoopDB only retain 10,000 or so records for live table (audit_event)

### ISSUE THREAD

**Issue by BobyMCbobs** [cncf/apisnoop#600]
When SnoopDB is deployed to a cluster with Auditlogger, if the database is left for a day or so it will cause the node to run out of memory or storage due to the number of requests.
A trigger should be added to SnoopDB so that once the database returns so many records in the audit_event table, it clears it out.

**Comment by zachmandeville** [comment]
I think we will want to do this as table partitions([postgres docs](https://www.postgresql.org/docs/current/ddl-partitioning.html)).  A triggered delete would be resource intensive and wouldn't necessarily free up the space on the machine([relevant SO discussion](https://stackoverflow.com/questions/49688137/postgresql-large-delete-from-500gb-db-auto-vacuum))

We could redesign the live.audit_event table to be partitioned, but would want to find the best column for our ranges.  Partitions are designed where you create the initial table, and then manually create the partitioned tables for each relevant range. I am not sure yet how we would want to do that for the audit events(e.g. based on time or entry id or some other factor), but would be good to research and discuss!

**Comment by zachmandeville** [comment]
In the meantime, the best workaround is to turn off the auditlogger via kubectl when you are leaving for the weekend (if you are keeping snoopdb up).

**Comment by Riaankl** [comment]
Good solution, thank you @zachmandeville
