### ISSUE TITLE
Align Summary Card to Sunburst Center

### ISSUE THREAD

**Issue by devaii** [cncf/apisnoop#62]
The "summary card" to the left of the sunburst graph, is currently aligned to match the top of the entire sunburst box, including the title. However, this causes the "summary card" look off-center on the page.

 I think it would be more appropriate to align the "summary card" to the center of the sunburst graph itself.

**Comment by zachmandeville** [comment]
@devaii , The sunburst summary has adjusted to include more details, including the test tags that hit the endpoint.  This end sup making the summary take up about the same height as the sunburst.  If we center the summary, there'll be an unappeaing jump whenever you hover over an endpoint with tests.   I'd recommend checking out #201 and seeing how the summary looks there, and perhaps we can adjust or close this ticket.

**Comment by zachmandeville** [comment]
as we will be making substantial changes to the summary card, as part of our ux/ui updates, and this ticket references alignment on a ui component hat may not be a part of the new ux, i am closing the ticket.
