### ISSUE TITLE
Add safety check in web frontend for releases with data

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#621]
there are scenarios where our list of releases includes a latest release that does not yet have data generated for it (e.g. there is not a corresponding {RELEASE}.json in our coverages directory for the web frontend to pull from).

To prevent the site from trying to show data it cannot retrieve, we can put a safety check in when the site organizes its list of releases.  the web frontend gathers the releases, then filters out any that don't have matching json, and from this filtered list creates its list of available releases.

## Context/example

When there  is a new release of kubernetes, we update our `releases.yaml` to show this new release.  Then, we generate testing data for it by running Snoopdb...which can take 5-15 minutes, depending.  During this period of time, the website will see the releases have updated, grab the latest one, and try to fetch its json...which isn't done generating.   We would instead have a safety check, so the site knows to ignore thhis release.  Once there is data, and someone visits the site, it would all work as expected.

**Comment by Riaankl** [comment]
Resolved, thank you @zachmandeville
