### ISSUE TITLE
`pages build and deployment` GHA is running is a loop

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#635]
Every time the PR created by `[pages build and deployment](https://github.com/cncf/apisnoop/actions/runs/3577831780)`get merged it trigger another run of the GHA.
Need to be disabled.

**Comment by BobyMCbobs** [comment]
<img width="813" alt="Screenshot 2022-11-30 at 09 48 26" src="https://user-images.githubusercontent.com/8588826/204644450-3bbb35b0-1915-4b15-b02a-7825267721db.png">

i was able to set Branch to None and it should be disabled now!

**Comment by Riaankl** [comment]
Tested and all seem OK!
Thank you for fixing this @BobyMCbobs
