### ISSUE TITLE
Update helm chart for GHA `apisnoop weekly updater` to alway use `snoopdb:latest`

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#664]
Ensure that the GHA will use most upto date version of APISnoop.

**Comment by cooldracula** [comment]
This is implemented in https://github.com/cncf/apisnoop/pull/667

Context for future readers:

Our workflows are rarely using the code as in the repo, and rather built images of the code.  snoopdb on a pair box will create everything from our helm charts, and this weekly updater had a specifically tagged image it was using as well.

The images are created automatically by google cloud build.  you can see a list of them here:
https://console.cloud.google.com/gcr/images/k8s-staging-apisnoop/GLOBAL/snoopdb

If we decide to not use `latest` then you just have to remember that, when we make some change to the db, to update charts/snoopdb/chart.yaml with the change and its listing in [apisnoop_weekly_updater.yml](https://github.com/cncf/apisnoop/blob/main/.github/workflows/apisnoop_weekly_updater.yml)

**Comment by Riaankl** [comment]
Fixed by https://github.com/cncf/apisnoop/pull/668
Thank you @zachmandeville
