### ISSUE TITLE
Filter API endpoints via regexp

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#67]
For untested API endpoints, we need to be able to filter without having any test tags or useragent data.

**Comment by hh** [comment]
@spiffxp https://dev.apisnoop.cncf.ci/?filter=storage currently supports string searches.
@zachmandeville can you look at http://xregexp.com?

**Comment by devaii** [comment]
Related to https://github.com/cncf/apisnoop/issues/75

**Comment by zachmandeville** [comment]
We are now able to do this, but the filter feature is disabled by default as we think usable, valuable filtering requires a bit more strategy and thought than a simple text field  We'll return to it after these discussions have happened.
