### ISSUE TITLE
Refactor conformance progress query and output to include pending endpoints

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#698]
We have a pending_endpoints yaml in the ii fork of kubernetes that show endpoints that are not yet conformant, but will be soon.

We want to include these endpoints in our conformance progress chart, so that we can see the work left to be done (e.g., writing tests for endpoints on the pending list).

The bar chart reads from our conformance-progress.json which is output directly from snoodb.  So adjust snoopdb's queries to read this pending_endpoints yaml and include it in our progress reports.

This will require adjustments to multiple tables, as pending endpoints is not yet read in and, following our existing patterns, will require its own table and loading function.

**Comment by Riaankl** [comment]
https://github.com/kubernetes/kubernetes/pull/115976 have merged.
Actions needed next:
- Point APISnoop to the main branch `pending_eligible_endpoints.yaml`
- Create a page that display the `pending_eligible_endpoints.yaml` as a page in APISnoop web (Like https://apisnoop.cncf.io/conformance-progress/ineligible-endpoints)
- add a hyperlink for  `pending_eligible_endpoints.yaml` page to the apisnoop home page at " exclude endpoints whose eligibility is pending"
