### ISSUE TITLE
Update DataSets, accounting for pre-1.11 lack of user-agent

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#73]
1.10 and 1.11 don't contain user agents so we need to show the full dataset for 1.12+.

- [x] Update processAuditlog.py to include non e2e.test traffic

**Comment by hh** [comment]
Current data set seems to ONLY have e2e, and not others.
Let's inspect the data set as created, and update the script to allow all user-agents.

**Comment by hh** [comment]
@zachmandeville and I paired on this yesterday.
We removed the filter and we'll now have the full logs for all user agents for next sprint.

**Comment by hh** [comment]
@zachmandeville can you ensure this was merged?

**Comment by zachmandeville** [comment]
It is not merged yet, @hh , but i can be easily after https://github.com/cncf/apisnoop/pull/109 is merged; or if you wanted to pair with me on some git-rebasing-foo.
