### ISSUE TITLE
Add automatic dependency and security updates

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#738]
in order to keep software update to date and the repo continuously active (to run CI jobs), automated dependency updates should be enabled through either dependabot or renovatebot. There must be a build step to ensure the app still builds before merging.

**Comment by BobyMCbobs** [comment]
Dependabot has been enabled and there are now security scans and some audits running

**Comment by BobyMCbobs** [comment]
One of the audits ran and unsurprising not verifying TLS is considered a high risk.

https://github.com/cncf-infra/verify-conformance/issues/64

**Comment by BobyMCbobs** [comment]
this is completed
