### ISSUE TITLE
Update to Go version 1.20

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#741]
Go version updates should be automated and tied into the `ko build` stage, like how I've done here: 
- https://github.com/BobyMCbobs/sample-ko-monorepo/blob/main/.github/workflows/reusable-update-go-version.yml
- https://github.com/BobyMCbobs/sample-ko-monorepo/blob/main/.github/workflows/reusable-build.yml#L55

It should end up with Go 1.20.

**Comment by BobyMCbobs** [comment]
fixed by https://github.com/cncf-infra/verify-conformance/commit/7aa51c15e97779b2a5ba7b06dc3dc6972423419e (in an automated way)
