### ISSUE TITLE
Remove e2e.log usage

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#743]
https://github.com/cncf-infra/verify-conformance/issues/43

**Comment by BobyMCbobs** [comment]
completed with https://github.com/cncf-infra/verify-conformance/pull/71

**Comment by BobyMCbobs** [comment]
since this change, two tests are no longer included and we are down to 13 tests.

**Comment by Riaankl** [comment]
@BobyMCbobs thank you for the update, please also update the [Requiements table](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#requirements) to reflect the change.

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs thank you for the update, please also update the [Requiements table](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#requirements) to reflect the change.

@Riaankl, good thinking; meant to make note of it, git was failing to clone it on Saturday. Gonna try again now.
