### ISSUE TITLE
Build in the stable.txt file

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#745]
- normally found at https://storage.googleapis.com/kubernetes-release/release/stable.txt and update automatically with actuallys, to improve expected behaviour (network)
- https://github.com/cncf-infra/verify-conformance/issues/42

**Comment by BobyMCbobs** [comment]
Had a flake after my changes
https://github.com/cncf/k8s-conformance/pull/2577#issuecomment-1536055496
<img width="928" alt="Screenshot 2023-05-05 at 22 33 19" src="https://user-images.githubusercontent.com/8588826/236435812-739ef383-d3e7-43b6-af70-53f8fe65688c.png">

Performed a 
```
🐚 kubectl -n prow rollout undo deployment verify-conformance-release
deployment.apps/verify-conformance-release rolled back
```

until I figure out what went wrong.

**Comment by BobyMCbobs** [comment]
this was resolved through adding unit tests in https://github.com/cncf-infra/verify-conformance/pull/72 and removing e2e.log usage https://github.com/cncf-infra/verify-conformance/pull/71
