### ISSUE TITLE
releases should always be sorted numerically

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#76]
In the latest dev branch, our releases are listed 1.10, 1.9, 1.11.  It should be 1.9, 1.10, 1.11.  This is how it works on the master branch, and so investigate why the sorting changed with the new data.

**Comment by zachmandeville** [comment]
Fixed in commit 02d32e4, and will be part of regex filter merge request

**Comment by hh** [comment]
I think with the UX update, we may have lost the sort.

**Comment by zachmandeville** [comment]
Fixed in 9d4fef4a8f7b2b049a92dd618747dc445cec0b05 , part of https://github.com/cncf/apisnoop/pull/109
