### ISSUE TITLE
Remove update-image action until we have a strategy for helm chart images

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#791]
We have a github action that is failing, because it is entirely commented out.  There is no "action" to do, so github throws an error.

This action, however, never _did_ anything.  It is a stalled thought.  Its initial intent was to update our helm charts with the latest created images from our google cloud action.

I think it would be good to remove this action entirely, as our helm charts are not set up for automation just yet.  It would be good to have a strategy for our images that our helm charts use, and then build a pipeline for that strategy.

Right now, whenever any commit is merged into main, images for our apps are created in our gcr repository (e.g. snoopdb and auditlogger).   These images are tagged with the date, the current latest tag of the apisnoop repo, a version number, and the commit hash.  There are a /lot/ of commits to main that don't affect the apps at all--since we are continually updating the coverage yaml files...so a lot of identical images, with new tags, are created.

When we make a major change to one of the apps, a change that we want reflected in the helm charts, our flow is to merge, watch GCR for the latest image, copy its tag, and then update the helm chart with this new tag. 

the purpose of the gh action `update-image` was to automate this process, so on merge to main, we grab the latest gcr image, and then we would adjust the helm chart and open a PR with this change...but this will cause a looping issue.  When we merge the updated chart, we'll make a new image, which will need to be added to the chart, etc.

I think our issue is not with the automation, but with the tagging of our images and how they show in the charts.  There is no easy meaning to be gained by the tags currently---e.g. looking at the helm chart doesn't give you any sense of how snoopdb will perform.

We should determine how we want to represent changes in our snoop apps.  Should snoopdb have semantic versioning?  Should there be a `stable` tag that helm uses, so the helm chart doesn't change but the `stable` snoopdb is adjusted over time?  When we have the right strategy, then we can build the automation. Until then, I think the file should be removed because it is confusing.

**Comment by Riaankl** [comment]
Fixed by https://github.com/cncf/apisnoop/pull/792
