### ISSUE TITLE
Create easy-to-automate flow for updating the web interface with new data

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#90]
```gherkin
Given that seeing our data visualized in the webui
And this is done by loading the data into the web's backend, to be consumed by the frontend
When we have a new set of processed data
Then there is an easy-to-automate flow to download the data into our web backend
And populate its api to be consumed by the frontend.
```

**Comment by hh** [comment]
## Document steps / update script:

### Create apisnoop.json and publish to GCS_PREFIX
- [ ] GCS_PREFIX=gs://apisnoop/$(git branch)/
- [ ] ./apisnoop.sh --update-cache
- [ ] ./apisnoop.sh --process-cache
- [ ] ./apisnoop.sh --upload-apiusage

### Start backend to pull from GCS_PREFIX
- [ ] GCS_PREFIX=gs://apisnoop/$(git branch)/
- [ ] ./apisnoop.sh --download-apiusage
- [ ] ./npm start

**Comment by zachmandeville** [comment]
I've refactored the front-end and backend to handle our new data flow, and the new information available to the web interface.  This is the core part of the work in https://github.com/cncf/apisnoop/pull/101 .  There's work to be done on styling it and improving the UX, but the core flow works for bringing in new data and having it populate our front and back end.

**Comment by hh** [comment]
Let's wrap up the styling, add the documentation to close this out.

**Comment by hh** [comment]
Let's simplify the link to the prow/spyglass but just list the job_bucket/number:
[ci-kubernetes-e2e-gci-gce/34681](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/34681)

**Comment by hh** [comment]
I had a chance to pair with the Globant devs and found it difficult to find the source apisnoop data.

We should add a link back to the unrendered, but processed APISnoop data.

**Comment by zachmandeville** [comment]
Updated sunburst header in https://github.com/cncf/apisnoop/pull/109/commits/4d984ae81517f901eac4cd2a9673a4be4e859263, but unsure if the link in there is the  one you are referring to for the processed apisnoop data, @hh .

**Comment by zachmandeville** [comment]
Release link now correct, as part of 91782b25408d796f365078699f3ceda9527f6020 in https://github.com/cncf/apisnoop/pull/109
