### ISSUE TITLE
Add a dev, staging, and production buckets for our data, and way to specify to which one new data should be sent

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#92]
```gherkin
GIVEN That we have different branches/stages of our development process
AND these different branches may want to have different data it pulls from
WHEN  when our command line tool wants to push newly processed data
THEN thetool can specify where it pushes this data.
AND we can have distinct buckets, and data sets, for the distinct branches of our dev cycle
AND the syntax and behavior of this process follows our documentation.
```

**Comment by hh** [comment]
Document setting GCS_BUCKET_PREFIX to possibly include  branch name or default to prod if on master.

**Comment by hh** [comment]
Let's look at documenting putting this into practice this week.

**Comment by devaii** [comment]
Created the following bucket prefixes: `gs://apisnoop/dev/` `gs://apisnoop/staging/` `gs://apisnoop/prod/`

Ability to specify bucket prefix added at: ca2b6daae7b4e6f4b24f0e2200be0fc7179c9fc2 

Documentation tracked here: https://github.com/cncf/apisnoop/issues/111
