### ISSUE TITLE
Webui backend pulls from our GCS bucket of processed data, instead of a local folder

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#96]
As an APISnoop developer wanting a persistent source for our data,
In order to avoid manually logging into our server to retrieve data,
and to avoid the time required to manually process this retrieved data,
I want a --consume script that pulls processed data, according to our sources.yml file, into our backend's data folder.

```cucumber
Given a sources.yml
And a GCS prefix that holds data processed by our apisnoop utility 
When I run a --consume script
Then it downloads the process data into our backend's local data folder
```

**Comment by hh** [comment]
@zachmandeville I'm feeling we have this with ```./apisnoop.sh --download-apiusage```
If you agree, go ahead and close this one.

**Comment by hh** [comment]
For now let's not have the backend application pull from GCS, we'll just run '--download-apiusage'

**Comment by zachmandeville** [comment]
We have our intended results now with the apisnoop cli.  The backend downloads from a GCS bucket, to a local folder, then updates its api using these new files.
