### ISSUE TITLE
Update our process-cache script to produce only a single json file

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#98]
As an APISnoop developer, who wants a simple process for bringing in new data to our backend services,
I want the existing 3 files generated by --process-cache to be a single, well-organized file; so I can reduce the logic necessary to starting up our backend service.

```gherkin
Given a cache of downloaded data
When --process-cache is run
Then it produces a single JSN for each release/build.
And this JSON contains the contents currently held in apisnoop.json, finished.json, and manifest.json
```

**Comment by zachmandeville** [comment]
related to #89

**Comment by hh** [comment]
Will revisit later in the week.

**Comment by hh** [comment]
@zachmandeville with our work on the backend startup today, let's go ahead and pull down multiple files.
